// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/account/account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEMALE",
	2: "MALE",
}

var Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"FEMALE":  1,
	"MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{0}
}

type RegisterReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterReq) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterResp struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// User信息, 应当在登录成功后返回给client, 需要给client知道的信息就往这里面加
type UserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{3}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{4}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type GetUserByAccountReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByAccountReq) Reset()         { *m = GetUserByAccountReq{} }
func (m *GetUserByAccountReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccountReq) ProtoMessage()    {}
func (*GetUserByAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{5}
}

func (m *GetUserByAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccountReq.Unmarshal(m, b)
}
func (m *GetUserByAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccountReq.Marshal(b, m, deterministic)
}
func (m *GetUserByAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccountReq.Merge(m, src)
}
func (m *GetUserByAccountReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccountReq.Size(m)
}
func (m *GetUserByAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccountReq proto.InternalMessageInfo

func (m *GetUserByAccountReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetUserByAccountResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserByAccountResp) Reset()         { *m = GetUserByAccountResp{} }
func (m *GetUserByAccountResp) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccountResp) ProtoMessage()    {}
func (*GetUserByAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{6}
}

func (m *GetUserByAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccountResp.Unmarshal(m, b)
}
func (m *GetUserByAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccountResp.Marshal(b, m, deterministic)
}
func (m *GetUserByAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccountResp.Merge(m, src)
}
func (m *GetUserByAccountResp) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccountResp.Size(m)
}
func (m *GetUserByAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccountResp proto.InternalMessageInfo

func (m *GetUserByAccountResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type GetUserByIdReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdReq) Reset()         { *m = GetUserByIdReq{} }
func (m *GetUserByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdReq) ProtoMessage()    {}
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{7}
}

func (m *GetUserByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdReq.Unmarshal(m, b)
}
func (m *GetUserByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdReq.Marshal(b, m, deterministic)
}
func (m *GetUserByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdReq.Merge(m, src)
}
func (m *GetUserByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdReq.Size(m)
}
func (m *GetUserByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdReq proto.InternalMessageInfo

func (m *GetUserByIdReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserByIdResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserByIdResp) Reset()         { *m = GetUserByIdResp{} }
func (m *GetUserByIdResp) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResp) ProtoMessage()    {}
func (*GetUserByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{8}
}

func (m *GetUserByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResp.Unmarshal(m, b)
}
func (m *GetUserByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResp.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResp.Merge(m, src)
}
func (m *GetUserByIdResp) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResp.Size(m)
}
func (m *GetUserByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResp proto.InternalMessageInfo

func (m *GetUserByIdResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("account.Gender", Gender_name, Gender_value)
	proto.RegisterType((*RegisterReq)(nil), "account.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "account.RegisterResp")
	proto.RegisterType((*UserInfo)(nil), "account.UserInfo")
	proto.RegisterType((*LoginReq)(nil), "account.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "account.LoginResp")
	proto.RegisterType((*GetUserByAccountReq)(nil), "account.GetUserByAccountReq")
	proto.RegisterType((*GetUserByAccountResp)(nil), "account.GetUserByAccountResp")
	proto.RegisterType((*GetUserByIdReq)(nil), "account.GetUserByIdReq")
	proto.RegisterType((*GetUserByIdResp)(nil), "account.GetUserByIdResp")
}

func init() { proto.RegisterFile("server/account/account.proto", fileDescriptor_56d089a9b5e998c0) }

var fileDescriptor_56d089a9b5e998c0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x6b, 0xda, 0x60,
	0x10, 0x37, 0x99, 0x4b, 0xe2, 0x65, 0x53, 0x77, 0x53, 0x0c, 0xc1, 0x81, 0xe4, 0x45, 0xb7, 0x81,
	0x19, 0xee, 0x69, 0xec, 0x65, 0x0a, 0x2a, 0x32, 0xe7, 0x68, 0x40, 0x0a, 0x7d, 0x29, 0x6a, 0x3e,
	0x43, 0x90, 0x26, 0x69, 0xbe, 0xd8, 0xd2, 0xb7, 0xd2, 0xf7, 0xfe, 0xcf, 0x25, 0x9f, 0x49, 0x8c,
	0x46, 0xa5, 0xf5, 0xc9, 0xbb, 0xfb, 0xdd, 0x77, 0xf7, 0xbb, 0xdf, 0x9d, 0x81, 0x3a, 0x25, 0xfe,
	0x1d, 0xf1, 0xf5, 0xd9, 0x62, 0xe1, 0xae, 0x9d, 0x20, 0xfe, 0x6d, 0x7b, 0xbe, 0x1b, 0xb8, 0x28,
	0x46, 0xae, 0xf6, 0xc8, 0x81, 0x6c, 0x10, 0xcb, 0xa6, 0x01, 0xf1, 0x0d, 0x72, 0x8b, 0x0a, 0xc4,
	0x90, 0xc2, 0x35, 0xb8, 0x56, 0xc1, 0x88, 0x5d, 0x54, 0x41, 0xf2, 0x66, 0x94, 0xde, 0xbb, 0xbe,
	0xa9, 0xf0, 0x0c, 0x4a, 0x7c, 0x44, 0xc8, 0x3b, 0xb3, 0x1b, 0xa2, 0xbc, 0x63, 0x71, 0x66, 0x63,
	0x13, 0x04, 0x8b, 0x38, 0x26, 0xf1, 0x95, 0x7c, 0x83, 0x6b, 0x15, 0x3b, 0xa5, 0x76, 0x4c, 0x61,
	0xc8, 0xc2, 0x46, 0x04, 0x6b, 0x4d, 0xf8, 0xb0, 0x65, 0x40, 0x3d, 0xac, 0x81, 0xb8, 0xa6, 0xc4,
	0xbf, 0xb6, 0x4d, 0x46, 0xe1, 0xa3, 0x21, 0x84, 0xee, 0xc8, 0xd4, 0x9e, 0x38, 0x90, 0xa6, 0xa1,
	0xe9, 0x2c, 0xdd, 0xa3, 0x59, 0xe9, 0x09, 0xf8, 0xcc, 0x04, 0x8e, 0xbd, 0x58, 0xa5, 0x98, 0x26,
	0xfe, 0xeb, 0xd9, 0xfe, 0x01, 0x69, 0xec, 0x5a, 0xb6, 0x73, 0xb6, 0x58, 0xda, 0x6f, 0x28, 0x44,
	0x15, 0xa8, 0x87, 0x6d, 0x28, 0x6c, 0xc6, 0x70, 0x96, 0x2e, 0x2b, 0x22, 0x77, 0x3e, 0x25, 0xad,
	0xe3, 0x61, 0x0d, 0x69, 0x1d, 0x59, 0x9a, 0x0e, 0x9f, 0x87, 0x24, 0x08, 0x81, 0xde, 0x43, 0x77,
	0x93, 0x76, 0x92, 0x89, 0x36, 0x80, 0x4a, 0xf6, 0xc1, 0x19, 0x8d, 0xbf, 0x42, 0x31, 0xa9, 0x33,
	0x32, 0xc3, 0x9e, 0x47, 0xf7, 0xd4, 0x85, 0xd2, 0x4e, 0xea, 0xdb, 0xbb, 0x7d, 0xfb, 0x0e, 0xc2,
	0x46, 0x77, 0x94, 0x41, 0x9c, 0x4e, 0xfe, 0x4e, 0xfe, 0x5f, 0x4e, 0xca, 0x39, 0x04, 0x10, 0x06,
	0xfd, 0x7f, 0xdd, 0x71, 0xbf, 0xcc, 0xa1, 0x04, 0x79, 0x66, 0xf1, 0x9d, 0x67, 0x1e, 0xc4, 0x68,
	0x34, 0xfc, 0x05, 0x52, 0x7c, 0x4c, 0x58, 0x49, 0x3a, 0xa4, 0x2e, 0x5c, 0xad, 0x1e, 0x88, 0x52,
	0x4f, 0xcb, 0xe1, 0x0f, 0x78, 0xcf, 0xf6, 0x82, 0x5b, 0x66, 0xf1, 0xa6, 0x55, 0xdc, 0x0f, 0xb1,
	0x17, 0x17, 0x50, 0xde, 0xd7, 0x16, 0xeb, 0xa9, 0xc3, 0xc9, 0xec, 0x49, 0xfd, 0x72, 0x02, 0x65,
	0x25, 0x7b, 0x20, 0xa7, 0xb4, 0xc3, 0x5a, 0x36, 0x9f, 0x89, 0xaf, 0x2a, 0x87, 0x81, 0xb0, 0x46,
	0xaf, 0x76, 0x55, 0xf5, 0x56, 0x96, 0xee, 0xcd, 0xf5, 0xdd, 0x6f, 0xc0, 0x5c, 0x60, 0x7f, 0xfe,
	0x9f, 0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xd4, 0x14, 0xfe, 0x1c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	GetUserByAccount(ctx context.Context, in *GetUserByAccountReq, opts ...grpc.CallOption) (*GetUserByAccountResp, error)
	GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/account.Account/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/account.Account/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserByAccount(ctx context.Context, in *GetUserByAccountReq, opts ...grpc.CallOption) (*GetUserByAccountResp, error) {
	out := new(GetUserByAccountResp)
	err := c.cc.Invoke(ctx, "/account.Account/GetUserByAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error) {
	out := new(GetUserByIdResp)
	err := c.cc.Invoke(ctx, "/account.Account/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	GetUserByAccount(context.Context, *GetUserByAccountReq) (*GetUserByAccountResp, error)
	GetUserById(context.Context, *GetUserByIdReq) (*GetUserByIdResp, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAccountServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAccountServer) GetUserByAccount(ctx context.Context, req *GetUserByAccountReq) (*GetUserByAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByAccount not implemented")
}
func (*UnimplementedAccountServer) GetUserById(ctx context.Context, req *GetUserByIdReq) (*GetUserByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUserByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserByAccount(ctx, req.(*GetUserByAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserById(ctx, req.(*GetUserByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Account_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
		{
			MethodName: "GetUserByAccount",
			Handler:    _Account_GetUserByAccount_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _Account_GetUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/account/account.proto",
}
