// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/account/account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEMALE",
	2: "MALE",
}

var Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"FEMALE":  1,
	"MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{0}
}

type AddUserReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{0}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AddUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddUserReq) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type AddUserResp struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResp) Reset()         { *m = AddUserResp{} }
func (m *AddUserResp) String() string { return proto.CompactTextString(m) }
func (*AddUserResp) ProtoMessage()    {}
func (*AddUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{1}
}

func (m *AddUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResp.Unmarshal(m, b)
}
func (m *AddUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResp.Marshal(b, m, deterministic)
}
func (m *AddUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResp.Merge(m, src)
}
func (m *AddUserResp) XXX_Size() int {
	return xxx_messageInfo_AddUserResp.Size(m)
}
func (m *AddUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResp proto.InternalMessageInfo

func (m *AddUserResp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// User信息, 应当在登录成功后返回给client, 需要给client知道的信息就往这里面加
type UserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type CheckPwdReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPwdReq) Reset()         { *m = CheckPwdReq{} }
func (m *CheckPwdReq) String() string { return proto.CompactTextString(m) }
func (*CheckPwdReq) ProtoMessage()    {}
func (*CheckPwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{3}
}

func (m *CheckPwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPwdReq.Unmarshal(m, b)
}
func (m *CheckPwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPwdReq.Marshal(b, m, deterministic)
}
func (m *CheckPwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPwdReq.Merge(m, src)
}
func (m *CheckPwdReq) XXX_Size() int {
	return xxx_messageInfo_CheckPwdReq.Size(m)
}
func (m *CheckPwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPwdReq proto.InternalMessageInfo

func (m *CheckPwdReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CheckPwdReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckPwdResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckPwdResp) Reset()         { *m = CheckPwdResp{} }
func (m *CheckPwdResp) String() string { return proto.CompactTextString(m) }
func (*CheckPwdResp) ProtoMessage()    {}
func (*CheckPwdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{4}
}

func (m *CheckPwdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPwdResp.Unmarshal(m, b)
}
func (m *CheckPwdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPwdResp.Marshal(b, m, deterministic)
}
func (m *CheckPwdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPwdResp.Merge(m, src)
}
func (m *CheckPwdResp) XXX_Size() int {
	return xxx_messageInfo_CheckPwdResp.Size(m)
}
func (m *CheckPwdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPwdResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPwdResp proto.InternalMessageInfo

func (m *CheckPwdResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type GetUserByAccountReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByAccountReq) Reset()         { *m = GetUserByAccountReq{} }
func (m *GetUserByAccountReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccountReq) ProtoMessage()    {}
func (*GetUserByAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{5}
}

func (m *GetUserByAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccountReq.Unmarshal(m, b)
}
func (m *GetUserByAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccountReq.Marshal(b, m, deterministic)
}
func (m *GetUserByAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccountReq.Merge(m, src)
}
func (m *GetUserByAccountReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccountReq.Size(m)
}
func (m *GetUserByAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccountReq proto.InternalMessageInfo

func (m *GetUserByAccountReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetUserByAccountResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserByAccountResp) Reset()         { *m = GetUserByAccountResp{} }
func (m *GetUserByAccountResp) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccountResp) ProtoMessage()    {}
func (*GetUserByAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{6}
}

func (m *GetUserByAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccountResp.Unmarshal(m, b)
}
func (m *GetUserByAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccountResp.Marshal(b, m, deterministic)
}
func (m *GetUserByAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccountResp.Merge(m, src)
}
func (m *GetUserByAccountResp) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccountResp.Size(m)
}
func (m *GetUserByAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccountResp proto.InternalMessageInfo

func (m *GetUserByAccountResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type GetUserByIdReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdReq) Reset()         { *m = GetUserByIdReq{} }
func (m *GetUserByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdReq) ProtoMessage()    {}
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{7}
}

func (m *GetUserByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdReq.Unmarshal(m, b)
}
func (m *GetUserByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdReq.Marshal(b, m, deterministic)
}
func (m *GetUserByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdReq.Merge(m, src)
}
func (m *GetUserByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdReq.Size(m)
}
func (m *GetUserByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdReq proto.InternalMessageInfo

func (m *GetUserByIdReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserByIdResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserByIdResp) Reset()         { *m = GetUserByIdResp{} }
func (m *GetUserByIdResp) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResp) ProtoMessage()    {}
func (*GetUserByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d089a9b5e998c0, []int{8}
}

func (m *GetUserByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResp.Unmarshal(m, b)
}
func (m *GetUserByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResp.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResp.Merge(m, src)
}
func (m *GetUserByIdResp) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResp.Size(m)
}
func (m *GetUserByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResp proto.InternalMessageInfo

func (m *GetUserByIdResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("account.Gender", Gender_name, Gender_value)
	proto.RegisterType((*AddUserReq)(nil), "account.AddUserReq")
	proto.RegisterType((*AddUserResp)(nil), "account.AddUserResp")
	proto.RegisterType((*UserInfo)(nil), "account.UserInfo")
	proto.RegisterType((*CheckPwdReq)(nil), "account.CheckPwdReq")
	proto.RegisterType((*CheckPwdResp)(nil), "account.CheckPwdResp")
	proto.RegisterType((*GetUserByAccountReq)(nil), "account.GetUserByAccountReq")
	proto.RegisterType((*GetUserByAccountResp)(nil), "account.GetUserByAccountResp")
	proto.RegisterType((*GetUserByIdReq)(nil), "account.GetUserByIdReq")
	proto.RegisterType((*GetUserByIdResp)(nil), "account.GetUserByIdResp")
}

func init() { proto.RegisterFile("server/account/account.proto", fileDescriptor_56d089a9b5e998c0) }

var fileDescriptor_56d089a9b5e998c0 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdf, 0x6b, 0xda, 0x50,
	0x14, 0x36, 0x99, 0x24, 0xf1, 0x64, 0x53, 0x77, 0x54, 0x0c, 0xc1, 0x81, 0xe4, 0x61, 0x73, 0x1b,
	0x18, 0x70, 0x30, 0xd8, 0xcb, 0x20, 0x8a, 0x8a, 0x6c, 0x73, 0x6d, 0x40, 0x0a, 0x7d, 0x29, 0x9a,
	0x5c, 0xad, 0x48, 0x93, 0x34, 0x57, 0x2b, 0x7d, 0x2a, 0xf4, 0x5f, 0xe8, 0x3f, 0x5c, 0x72, 0x4d,
	0x62, 0x6c, 0x54, 0x5a, 0x9f, 0x72, 0xce, 0xf9, 0xbe, 0x9c, 0xf3, 0x9d, 0x1f, 0x5c, 0xa8, 0x51,
	0xe2, 0xdf, 0x11, 0x5f, 0x1f, 0x5b, 0x96, 0xbb, 0x72, 0x96, 0xd1, 0xb7, 0xe9, 0xf9, 0xee, 0xd2,
	0x45, 0x31, 0x74, 0xb5, 0x07, 0x00, 0xc3, 0xb6, 0x47, 0x94, 0xf8, 0x26, 0xb9, 0x45, 0x05, 0x22,
	0x40, 0xe1, 0xea, 0x5c, 0x23, 0x67, 0x46, 0x2e, 0xaa, 0x20, 0x79, 0x63, 0x4a, 0xd7, 0xae, 0x6f,
	0x2b, 0x3c, 0x83, 0x62, 0x1f, 0x11, 0xb2, 0xce, 0xf8, 0x86, 0x28, 0xef, 0x58, 0x9c, 0xd9, 0xf8,
	0x05, 0x84, 0x19, 0x71, 0x6c, 0xe2, 0x2b, 0xd9, 0x3a, 0xd7, 0xc8, 0xb7, 0x0a, 0xcd, 0x48, 0x40,
	0x9f, 0x85, 0xcd, 0x10, 0xd6, 0x3e, 0x83, 0x1c, 0x0b, 0xa0, 0x1e, 0x56, 0x41, 0x5c, 0x51, 0xe2,
	0x5f, 0xcd, 0x6d, 0xa6, 0xe0, 0x83, 0x29, 0x04, 0xee, 0xc0, 0xd6, 0x1e, 0x39, 0x90, 0x02, 0xd6,
	0xc0, 0x99, 0xba, 0x07, 0x59, 0xc9, 0x06, 0xf8, 0x54, 0x03, 0xce, 0xdc, 0x5a, 0x24, 0x84, 0xc6,
	0xfe, 0xeb, 0xc5, 0x76, 0x40, 0xee, 0x5c, 0x13, 0x6b, 0x71, 0xb6, 0xb6, 0x4f, 0x1e, 0x97, 0xf6,
	0x1b, 0xde, 0x6f, 0x93, 0x50, 0x0f, 0x9b, 0x90, 0xdb, 0x34, 0xe3, 0x4c, 0x5d, 0x96, 0x47, 0x6e,
	0x7d, 0x8c, 0x05, 0x44, 0x2d, 0x9b, 0xd2, 0x2a, 0xb4, 0x34, 0x1d, 0x4a, 0x7d, 0xb2, 0x0c, 0x80,
	0xf6, 0xbd, 0xb1, 0xa1, 0x1d, 0x15, 0xa3, 0xf5, 0xa0, 0x9c, 0xfe, 0xe1, 0x84, 0xc2, 0x5f, 0x21,
	0x1f, 0xe7, 0x19, 0xb0, 0x01, 0x1c, 0xdc, 0x96, 0x01, 0x85, 0x1d, 0xea, 0xdb, 0xab, 0x7d, 0xfb,
	0x0e, 0xc2, 0x66, 0xfa, 0x28, 0x83, 0x38, 0x1a, 0xfe, 0x19, 0xfe, 0xbf, 0x18, 0x16, 0x33, 0x08,
	0x20, 0xf4, 0xba, 0xff, 0x8c, 0xbf, 0xdd, 0x22, 0x87, 0x12, 0x64, 0x99, 0xc5, 0xb7, 0x9e, 0x78,
	0x10, 0xc3, 0xd6, 0xf0, 0x27, 0x88, 0xe1, 0x45, 0x61, 0x29, 0x2e, 0xb0, 0x3d, 0x72, 0xb5, 0x9c,
	0x0e, 0x52, 0x4f, 0xcb, 0xe0, 0x2f, 0x90, 0xa2, 0xbd, 0xe0, 0x96, 0x93, 0xd8, 0xb7, 0x5a, 0xd9,
	0x13, 0x65, 0xbf, 0x9e, 0x43, 0xf1, 0xe5, 0x84, 0xb1, 0x96, 0x38, 0xa2, 0xd4, 0xb6, 0xd4, 0x4f,
	0x47, 0x50, 0x96, 0xb2, 0x0d, 0x72, 0x62, 0x82, 0x58, 0x4d, 0xf3, 0xd9, 0x0a, 0x54, 0x65, 0x3f,
	0x10, 0xe4, 0x68, 0x57, 0x2f, 0x2b, 0xde, 0x62, 0xa6, 0x7b, 0x13, 0x7d, 0xf7, 0x31, 0x98, 0x08,
	0xec, 0x15, 0xf8, 0xf1, 0x1c, 0x00, 0x00, 0xff, 0xff, 0x74, 0x4d, 0x7f, 0x33, 0x25, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error)
	CheckPwd(ctx context.Context, in *CheckPwdReq, opts ...grpc.CallOption) (*CheckPwdResp, error)
	GetUserByAccount(ctx context.Context, in *GetUserByAccountReq, opts ...grpc.CallOption) (*GetUserByAccountResp, error)
	GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	out := new(AddUserResp)
	err := c.cc.Invoke(ctx, "/account.Account/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) CheckPwd(ctx context.Context, in *CheckPwdReq, opts ...grpc.CallOption) (*CheckPwdResp, error) {
	out := new(CheckPwdResp)
	err := c.cc.Invoke(ctx, "/account.Account/CheckPwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserByAccount(ctx context.Context, in *GetUserByAccountReq, opts ...grpc.CallOption) (*GetUserByAccountResp, error) {
	out := new(GetUserByAccountResp)
	err := c.cc.Invoke(ctx, "/account.Account/GetUserByAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error) {
	out := new(GetUserByIdResp)
	err := c.cc.Invoke(ctx, "/account.Account/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	AddUser(context.Context, *AddUserReq) (*AddUserResp, error)
	CheckPwd(context.Context, *CheckPwdReq) (*CheckPwdResp, error)
	GetUserByAccount(context.Context, *GetUserByAccountReq) (*GetUserByAccountResp, error)
	GetUserById(context.Context, *GetUserByIdReq) (*GetUserByIdResp, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) AddUser(ctx context.Context, req *AddUserReq) (*AddUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedAccountServer) CheckPwd(ctx context.Context, req *CheckPwdReq) (*CheckPwdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPwd not implemented")
}
func (*UnimplementedAccountServer) GetUserByAccount(ctx context.Context, req *GetUserByAccountReq) (*GetUserByAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByAccount not implemented")
}
func (*UnimplementedAccountServer) GetUserById(ctx context.Context, req *GetUserByIdReq) (*GetUserByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_CheckPwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CheckPwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/CheckPwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CheckPwd(ctx, req.(*CheckPwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUserByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserByAccount(ctx, req.(*GetUserByAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserById(ctx, req.(*GetUserByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Account_AddUser_Handler,
		},
		{
			MethodName: "CheckPwd",
			Handler:    _Account_CheckPwd_Handler,
		},
		{
			MethodName: "GetUserByAccount",
			Handler:    _Account_GetUserByAccount_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _Account_GetUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/account/account.proto",
}
