// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEMALE",
	2: "MALE",
}

var Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"FEMALE":  1,
	"MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{0}
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Balance              int64     `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Token                string    `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *LoginResp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{3}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterResp struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{4}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RechargeReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta                int64    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeReq) Reset()         { *m = RechargeReq{} }
func (m *RechargeReq) String() string { return proto.CompactTextString(m) }
func (*RechargeReq) ProtoMessage()    {}
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{5}
}

func (m *RechargeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeReq.Unmarshal(m, b)
}
func (m *RechargeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeReq.Marshal(b, m, deterministic)
}
func (m *RechargeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeReq.Merge(m, src)
}
func (m *RechargeReq) XXX_Size() int {
	return xxx_messageInfo_RechargeReq.Size(m)
}
func (m *RechargeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeReq proto.InternalMessageInfo

func (m *RechargeReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RechargeReq) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *RechargeReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RechargeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeResp) Reset()         { *m = RechargeResp{} }
func (m *RechargeResp) String() string { return proto.CompactTextString(m) }
func (*RechargeResp) ProtoMessage()    {}
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{6}
}

func (m *RechargeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeResp.Unmarshal(m, b)
}
func (m *RechargeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeResp.Marshal(b, m, deterministic)
}
func (m *RechargeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeResp.Merge(m, src)
}
func (m *RechargeResp) XXX_Size() int {
	return xxx_messageInfo_RechargeResp.Size(m)
}
func (m *RechargeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeResp proto.InternalMessageInfo

type GetTopUserReq struct {
	Top                  uint32   `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopUserReq) Reset()         { *m = GetTopUserReq{} }
func (m *GetTopUserReq) String() string { return proto.CompactTextString(m) }
func (*GetTopUserReq) ProtoMessage()    {}
func (*GetTopUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{7}
}

func (m *GetTopUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopUserReq.Unmarshal(m, b)
}
func (m *GetTopUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopUserReq.Marshal(b, m, deterministic)
}
func (m *GetTopUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopUserReq.Merge(m, src)
}
func (m *GetTopUserReq) XXX_Size() int {
	return xxx_messageInfo_GetTopUserReq.Size(m)
}
func (m *GetTopUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopUserReq proto.InternalMessageInfo

func (m *GetTopUserReq) GetTop() uint32 {
	if m != nil {
		return m.Top
	}
	return 0
}

type GetTopUserResp struct {
	UserList             string   `protobuf:"bytes,1,opt,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopUserResp) Reset()         { *m = GetTopUserResp{} }
func (m *GetTopUserResp) String() string { return proto.CompactTextString(m) }
func (*GetTopUserResp) ProtoMessage()    {}
func (*GetTopUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{8}
}

func (m *GetTopUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopUserResp.Unmarshal(m, b)
}
func (m *GetTopUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopUserResp.Marshal(b, m, deterministic)
}
func (m *GetTopUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopUserResp.Merge(m, src)
}
func (m *GetTopUserResp) XXX_Size() int {
	return xxx_messageInfo_GetTopUserResp.Size(m)
}
func (m *GetTopUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopUserResp proto.InternalMessageInfo

func (m *GetTopUserResp) GetUserList() string {
	if m != nil {
		return m.UserList
	}
	return ""
}

type OrderNotPayReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderNotPayReq) Reset()         { *m = OrderNotPayReq{} }
func (m *OrderNotPayReq) String() string { return proto.CompactTextString(m) }
func (*OrderNotPayReq) ProtoMessage()    {}
func (*OrderNotPayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{9}
}

func (m *OrderNotPayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderNotPayReq.Unmarshal(m, b)
}
func (m *OrderNotPayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderNotPayReq.Marshal(b, m, deterministic)
}
func (m *OrderNotPayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderNotPayReq.Merge(m, src)
}
func (m *OrderNotPayReq) XXX_Size() int {
	return xxx_messageInfo_OrderNotPayReq.Size(m)
}
func (m *OrderNotPayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderNotPayReq.DiscardUnknown(m)
}

var xxx_messageInfo_OrderNotPayReq proto.InternalMessageInfo

func (m *OrderNotPayReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type OrderNotPayResp struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderNotPayResp) Reset()         { *m = OrderNotPayResp{} }
func (m *OrderNotPayResp) String() string { return proto.CompactTextString(m) }
func (*OrderNotPayResp) ProtoMessage()    {}
func (*OrderNotPayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{10}
}

func (m *OrderNotPayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderNotPayResp.Unmarshal(m, b)
}
func (m *OrderNotPayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderNotPayResp.Marshal(b, m, deterministic)
}
func (m *OrderNotPayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderNotPayResp.Merge(m, src)
}
func (m *OrderNotPayResp) XXX_Size() int {
	return xxx_messageInfo_OrderNotPayResp.Size(m)
}
func (m *OrderNotPayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderNotPayResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderNotPayResp proto.InternalMessageInfo

func (m *OrderNotPayResp) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayReq) Reset()         { *m = PayReq{} }
func (m *PayReq) String() string { return proto.CompactTextString(m) }
func (*PayReq) ProtoMessage()    {}
func (*PayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{11}
}

func (m *PayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayReq.Unmarshal(m, b)
}
func (m *PayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayReq.Marshal(b, m, deterministic)
}
func (m *PayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayReq.Merge(m, src)
}
func (m *PayReq) XXX_Size() int {
	return xxx_messageInfo_PayReq.Size(m)
}
func (m *PayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayReq proto.InternalMessageInfo

func (m *PayReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResp) Reset()         { *m = PayResp{} }
func (m *PayResp) String() string { return proto.CompactTextString(m) }
func (*PayResp) ProtoMessage()    {}
func (*PayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{12}
}

func (m *PayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResp.Unmarshal(m, b)
}
func (m *PayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResp.Marshal(b, m, deterministic)
}
func (m *PayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResp.Merge(m, src)
}
func (m *PayResp) XXX_Size() int {
	return xxx_messageInfo_PayResp.Size(m)
}
func (m *PayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("user.Gender", Gender_name, Gender_value)
	proto.RegisterType((*LoginReq)(nil), "user.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "user.LoginResp")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*RegisterReq)(nil), "user.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "user.RegisterResp")
	proto.RegisterType((*RechargeReq)(nil), "user.RechargeReq")
	proto.RegisterType((*RechargeResp)(nil), "user.RechargeResp")
	proto.RegisterType((*GetTopUserReq)(nil), "user.GetTopUserReq")
	proto.RegisterType((*GetTopUserResp)(nil), "user.GetTopUserResp")
	proto.RegisterType((*OrderNotPayReq)(nil), "user.OrderNotPayReq")
	proto.RegisterType((*OrderNotPayResp)(nil), "user.OrderNotPayResp")
	proto.RegisterType((*PayReq)(nil), "user.PayReq")
	proto.RegisterType((*PayResp)(nil), "user.PayResp")
}

func init() { proto.RegisterFile("logic/user.proto", fileDescriptor_cb7020df1c2f819c) }

var fileDescriptor_cb7020df1c2f819c = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0xc4, 0x71, 0x26, 0x8d, 0x9b, 0x4e, 0x83, 0xb0, 0x7c, 0x2a, 0xab, 0x4a, 0x94,
	0x06, 0x35, 0x52, 0x7a, 0x42, 0xe2, 0x00, 0x48, 0xa5, 0xaa, 0x08, 0x29, 0xb2, 0x28, 0x48, 0x5c,
	0x90, 0x63, 0x6f, 0x5d, 0x2b, 0xc1, 0xbb, 0x78, 0x1d, 0x21, 0x4e, 0x9c, 0xf8, 0x2a, 0x7e, 0x0e,
	0xed, 0x7a, 0x1d, 0x3b, 0x84, 0x70, 0x40, 0xbd, 0xed, 0x9b, 0x9d, 0x79, 0x33, 0xf3, 0xde, 0xda,
	0x30, 0x58, 0xb2, 0x38, 0x09, 0xc7, 0x2b, 0x41, 0xb3, 0x33, 0x9e, 0xb1, 0x9c, 0x61, 0x4b, 0x9e,
	0xc9, 0x0b, 0xb0, 0xa7, 0x2c, 0x4e, 0x52, 0x9f, 0x7e, 0x45, 0x17, 0x3a, 0x41, 0x18, 0xb2, 0x55,
	0x9a, 0xbb, 0xc6, 0x91, 0x71, 0xd2, 0xf5, 0x4b, 0x88, 0x1e, 0xd8, 0x3c, 0x10, 0xe2, 0x1b, 0xcb,
	0x22, 0xb7, 0xa9, 0xae, 0xd6, 0x98, 0xdc, 0x41, 0x57, 0x33, 0x08, 0x8e, 0x23, 0xe8, 0x4a, 0xda,
	0xcf, 0x49, 0x7a, 0xcb, 0x14, 0x49, 0x6f, 0xe2, 0x9c, 0xa9, 0xa6, 0x37, 0x82, 0x66, 0x57, 0xe9,
	0x2d, 0xf3, 0xed, 0x95, 0x3e, 0xc9, 0x7e, 0xf3, 0x60, 0x19, 0xa4, 0x21, 0x55, 0xa4, 0xa6, 0x5f,
	0x42, 0x1c, 0x42, 0x3b, 0x67, 0x0b, 0x9a, 0xba, 0xa6, 0x6a, 0x56, 0x00, 0xf2, 0x03, 0xec, 0x92,
	0x05, 0x1f, 0x42, 0xa7, 0x68, 0x14, 0xa9, 0x36, 0x7d, 0xdf, 0x52, 0xb4, 0x51, 0x7d, 0x89, 0xe6,
	0xd6, 0x12, 0x69, 0x12, 0x2e, 0xd2, 0xe0, 0x0b, 0xd5, 0xbc, 0x6b, 0x8c, 0xc7, 0x60, 0xc5, 0x34,
	0x8d, 0x68, 0xe6, 0xb6, 0x8e, 0x8c, 0x13, 0x67, 0xb2, 0x57, 0x0c, 0x7d, 0xa9, 0x62, 0xbe, 0xbe,
	0x23, 0x3f, 0x0d, 0xe8, 0xf9, 0x34, 0x4e, 0x44, 0x4e, 0xb3, 0xff, 0x16, 0xec, 0x1e, 0xe6, 0x78,
	0x0c, 0x7b, 0xd5, 0x18, 0x82, 0xef, 0x14, 0x83, 0x7c, 0x90, 0xf3, 0x86, 0x77, 0x41, 0x16, 0x53,
	0x39, 0xef, 0x4e, 0xd1, 0x86, 0xd0, 0x8e, 0xe8, 0x32, 0x0f, 0xb4, 0x0f, 0x05, 0xa8, 0xaf, 0x67,
	0x6e, 0xac, 0x47, 0x1c, 0x39, 0x40, 0xc9, 0x2b, 0x38, 0x79, 0x04, 0xfd, 0x4b, 0x9a, 0xbf, 0x67,
	0x5c, 0xfa, 0x23, 0x3b, 0x0d, 0xc0, 0xcc, 0x19, 0xd7, 0x5d, 0xe4, 0x91, 0x3c, 0x05, 0xa7, 0x9e,
	0x22, 0xb8, 0xd4, 0x41, 0xb6, 0x9f, 0x26, 0xa2, 0x94, 0x6f, 0x8d, 0xc9, 0x13, 0x70, 0xae, 0xb3,
	0x88, 0x66, 0x33, 0x96, 0xbf, 0x0b, 0xbe, 0xff, 0x6b, 0x76, 0x32, 0x82, 0xfd, 0x8d, 0x54, 0xc1,
	0xe5, 0xe0, 0x4c, 0x86, 0xae, 0xa2, 0xd2, 0x17, 0x0d, 0x09, 0x01, 0x4b, 0xf3, 0xed, 0xce, 0xe9,
	0x42, 0x47, 0x13, 0x9d, 0x8e, 0xc0, 0x2a, 0xa4, 0xc7, 0x1e, 0x74, 0x6e, 0x66, 0x6f, 0x66, 0xd7,
	0x1f, 0x67, 0x83, 0x06, 0x02, 0x58, 0xaf, 0x2f, 0xde, 0xbe, 0x9c, 0x5e, 0x0c, 0x0c, 0xb4, 0xa1,
	0xa5, 0x4e, 0xcd, 0xc9, 0xaf, 0x26, 0xb4, 0xe4, 0x72, 0x78, 0x0a, 0x6d, 0xf5, 0x45, 0xa0, 0x7e,
	0xfa, 0xe5, 0x07, 0xe6, 0xed, 0x6f, 0x60, 0xc1, 0x49, 0x03, 0xcf, 0xc1, 0x2e, 0xad, 0xc4, 0x83,
	0xe2, 0xba, 0xf6, 0xc2, 0x3c, 0xfc, 0x33, 0x54, 0x15, 0x15, 0xf2, 0x57, 0x45, 0x6b, 0x9b, 0xab,
	0xa2, 0x9a, 0x43, 0x0d, 0x7c, 0x06, 0x50, 0x19, 0x80, 0x87, 0xe5, 0xc3, 0xaa, 0xb9, 0xe6, 0x0d,
	0xb7, 0x83, 0xaa, 0xf4, 0x39, 0xf4, 0x6a, 0x12, 0xa3, 0x4e, 0xdb, 0x34, 0xc8, 0x7b, 0xf0, 0x97,
	0xa8, 0xaa, 0x3e, 0x06, 0x53, 0x56, 0xe9, 0xa7, 0xac, 0xb3, 0xfb, 0x35, 0x24, 0xb3, 0x5e, 0x1d,
	0x7e, 0x3a, 0xe0, 0x8b, 0x78, 0xcc, 0xe7, 0xe3, 0xea, 0x4f, 0x35, 0xb7, 0xd4, 0xaf, 0xea, 0xfc,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xaf, 0x95, 0x3d, 0xbe, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error)
	GetTopUser(ctx context.Context, in *GetTopUserReq, opts ...grpc.CallOption) (*GetTopUserResp, error)
	OrderNotPay(ctx context.Context, in *OrderNotPayReq, opts ...grpc.CallOption) (*OrderNotPayResp, error)
	Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/user.User/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/user.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error) {
	out := new(RechargeResp)
	err := c.cc.Invoke(ctx, "/user.User/Recharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetTopUser(ctx context.Context, in *GetTopUserReq, opts ...grpc.CallOption) (*GetTopUserResp, error) {
	out := new(GetTopUserResp)
	err := c.cc.Invoke(ctx, "/user.User/GetTopUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) OrderNotPay(ctx context.Context, in *OrderNotPayReq, opts ...grpc.CallOption) (*OrderNotPayResp, error) {
	out := new(OrderNotPayResp)
	err := c.cc.Invoke(ctx, "/user.User/OrderNotPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	out := new(PayResp)
	err := c.cc.Invoke(ctx, "/user.User/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Recharge(context.Context, *RechargeReq) (*RechargeResp, error)
	GetTopUser(context.Context, *GetTopUserReq) (*GetTopUserResp, error)
	OrderNotPay(context.Context, *OrderNotPayReq) (*OrderNotPayResp, error)
	Pay(context.Context, *PayReq) (*PayResp, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServer) Recharge(ctx context.Context, req *RechargeReq) (*RechargeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recharge not implemented")
}
func (*UnimplementedUserServer) GetTopUser(ctx context.Context, req *GetTopUserReq) (*GetTopUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUser not implemented")
}
func (*UnimplementedUserServer) OrderNotPay(ctx context.Context, req *OrderNotPayReq) (*OrderNotPayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderNotPay not implemented")
}
func (*UnimplementedUserServer) Pay(ctx context.Context, req *PayReq) (*PayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Recharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Recharge(ctx, req.(*RechargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetTopUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetTopUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetTopUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetTopUser(ctx, req.(*GetTopUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_OrderNotPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderNotPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).OrderNotPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/OrderNotPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).OrderNotPay(ctx, req.(*OrderNotPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Pay(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Recharge",
			Handler:    _User_Recharge_Handler,
		},
		{
			MethodName: "GetTopUser",
			Handler:    _User_GetTopUser_Handler,
		},
		{
			MethodName: "OrderNotPay",
			Handler:    _User_OrderNotPay_Handler,
		},
		{
			MethodName: "Pay",
			Handler:    _User_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic/user.proto",
}
