// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEMALE",
	2: "MALE",
}

var Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"FEMALE":  1,
	"MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{0}
}

type CheckUserPwdReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserPwdReq) Reset()         { *m = CheckUserPwdReq{} }
func (m *CheckUserPwdReq) String() string { return proto.CompactTextString(m) }
func (*CheckUserPwdReq) ProtoMessage()    {}
func (*CheckUserPwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{0}
}

func (m *CheckUserPwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserPwdReq.Unmarshal(m, b)
}
func (m *CheckUserPwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserPwdReq.Marshal(b, m, deterministic)
}
func (m *CheckUserPwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserPwdReq.Merge(m, src)
}
func (m *CheckUserPwdReq) XXX_Size() int {
	return xxx_messageInfo_CheckUserPwdReq.Size(m)
}
func (m *CheckUserPwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserPwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserPwdReq proto.InternalMessageInfo

func (m *CheckUserPwdReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CheckUserPwdReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckUserPwdResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Balance              int64     `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckUserPwdResp) Reset()         { *m = CheckUserPwdResp{} }
func (m *CheckUserPwdResp) String() string { return proto.CompactTextString(m) }
func (*CheckUserPwdResp) ProtoMessage()    {}
func (*CheckUserPwdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{1}
}

func (m *CheckUserPwdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserPwdResp.Unmarshal(m, b)
}
func (m *CheckUserPwdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserPwdResp.Marshal(b, m, deterministic)
}
func (m *CheckUserPwdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserPwdResp.Merge(m, src)
}
func (m *CheckUserPwdResp) XXX_Size() int {
	return xxx_messageInfo_CheckUserPwdResp.Size(m)
}
func (m *CheckUserPwdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserPwdResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserPwdResp proto.InternalMessageInfo

func (m *CheckUserPwdResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *CheckUserPwdResp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type UserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{3}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterResp struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{4}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RechargeReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta                int64    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeReq) Reset()         { *m = RechargeReq{} }
func (m *RechargeReq) String() string { return proto.CompactTextString(m) }
func (*RechargeReq) ProtoMessage()    {}
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{5}
}

func (m *RechargeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeReq.Unmarshal(m, b)
}
func (m *RechargeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeReq.Marshal(b, m, deterministic)
}
func (m *RechargeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeReq.Merge(m, src)
}
func (m *RechargeReq) XXX_Size() int {
	return xxx_messageInfo_RechargeReq.Size(m)
}
func (m *RechargeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeReq proto.InternalMessageInfo

func (m *RechargeReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RechargeReq) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type RechargeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeResp) Reset()         { *m = RechargeResp{} }
func (m *RechargeResp) String() string { return proto.CompactTextString(m) }
func (*RechargeResp) ProtoMessage()    {}
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb7020df1c2f819c, []int{6}
}

func (m *RechargeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeResp.Unmarshal(m, b)
}
func (m *RechargeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeResp.Marshal(b, m, deterministic)
}
func (m *RechargeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeResp.Merge(m, src)
}
func (m *RechargeResp) XXX_Size() int {
	return xxx_messageInfo_RechargeResp.Size(m)
}
func (m *RechargeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("user.Gender", Gender_name, Gender_value)
	proto.RegisterType((*CheckUserPwdReq)(nil), "user.CheckUserPwdReq")
	proto.RegisterType((*CheckUserPwdResp)(nil), "user.CheckUserPwdResp")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*RegisterReq)(nil), "user.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "user.RegisterResp")
	proto.RegisterType((*RechargeReq)(nil), "user.RechargeReq")
	proto.RegisterType((*RechargeResp)(nil), "user.RechargeResp")
}

func init() { proto.RegisterFile("logic/user.proto", fileDescriptor_cb7020df1c2f819c) }

var fileDescriptor_cb7020df1c2f819c = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x50, 0x4b, 0x19, 0x10, 0xcb, 0xfa, 0xd5, 0x70, 0x22, 0x1b, 0x13, 0x89, 0x24, 0x90,
	0xc0, 0xd5, 0x8b, 0x1f, 0x48, 0x8c, 0x8a, 0xa6, 0x09, 0x31, 0x7a, 0x31, 0xa5, 0x5d, 0x4a, 0x03,
	0xb6, 0x6b, 0xb7, 0x84, 0xa3, 0x27, 0xff, 0x92, 0xbf, 0xcf, 0xec, 0x2e, 0xa5, 0x88, 0x72, 0x31,
	0xde, 0xe6, 0xcd, 0xce, 0xbc, 0x79, 0xf3, 0x76, 0x17, 0x8c, 0x69, 0xe8, 0xf9, 0x4e, 0x6b, 0xc6,
	0x48, 0xd4, 0xa4, 0x51, 0x18, 0x87, 0x48, 0xe5, 0x31, 0xee, 0xc1, 0xce, 0xc5, 0x98, 0x38, 0x93,
	0x01, 0x23, 0xd1, 0xc3, 0xdc, 0xb5, 0xc8, 0x1b, 0x32, 0x21, 0x6f, 0x3b, 0x4e, 0x38, 0x0b, 0x62,
	0x53, 0xa9, 0x29, 0xf5, 0x82, 0x95, 0x40, 0x54, 0x05, 0x9d, 0xda, 0x8c, 0xcd, 0xc3, 0xc8, 0x35,
	0xb3, 0xe2, 0x68, 0x89, 0xf1, 0x13, 0x18, 0xdf, 0x89, 0x18, 0x45, 0x0d, 0x28, 0xf0, 0x21, 0x2f,
	0x7e, 0x30, 0x0a, 0x05, 0x57, 0xb1, 0x5d, 0x6e, 0x0a, 0x09, 0xbc, 0xea, 0x3a, 0x18, 0x85, 0x96,
	0x3e, 0x5b, 0x44, 0x7c, 0xec, 0xd0, 0x9e, 0xda, 0x81, 0x43, 0x04, 0x77, 0xce, 0x4a, 0x20, 0x7e,
	0x07, 0x3d, 0xa9, 0x47, 0x87, 0x90, 0x97, 0x94, 0xae, 0x20, 0xdc, 0xb6, 0x34, 0x41, 0xe0, 0xae,
	0xaa, 0xce, 0xfe, 0x50, 0x1d, 0xf8, 0xce, 0x24, 0xb0, 0x5f, 0x89, 0x99, 0x93, 0xaa, 0x13, 0x8c,
	0x8e, 0x40, 0xf3, 0x48, 0xe0, 0x92, 0xc8, 0x54, 0x6b, 0x4a, 0xbd, 0xdc, 0x2e, 0x49, 0x79, 0x3d,
	0x91, 0xb3, 0x16, 0x67, 0xf8, 0x43, 0x81, 0xa2, 0x45, 0x3c, 0x9f, 0xc5, 0x24, 0xfa, 0xb3, 0x43,
	0xff, 0xa0, 0xe3, 0x18, 0x4a, 0xa9, 0x0c, 0x46, 0x37, 0x9a, 0x81, 0x4f, 0xb9, 0x5e, 0x67, 0x6c,
	0x47, 0x1e, 0xe1, 0x7a, 0x37, 0x9a, 0xb6, 0x07, 0x5b, 0x2e, 0x99, 0xc6, 0xf6, 0xc2, 0x71, 0x09,
	0x70, 0x99, 0x8f, 0x49, 0xba, 0x19, 0x3d, 0x69, 0x80, 0x26, 0x85, 0xa0, 0x22, 0xe4, 0x07, 0xfd,
	0x9b, 0xfe, 0xfd, 0x63, 0xdf, 0xc8, 0x20, 0x00, 0xed, 0xaa, 0x7b, 0x77, 0x76, 0xdb, 0x35, 0x14,
	0xa4, 0x83, 0x2a, 0xa2, 0x6c, 0xfb, 0x53, 0x01, 0x95, 0xdf, 0x16, 0xba, 0x84, 0x4a, 0xfa, 0x20,
	0x12, 0x0f, 0xf6, 0xe5, 0x5e, 0x6b, 0x4f, 0xae, 0x7a, 0xf0, 0x5b, 0x9a, 0x51, 0x9c, 0x41, 0x1d,
	0xd0, 0x93, 0x95, 0x51, 0x45, 0x56, 0xad, 0xdc, 0x44, 0x15, 0xad, 0xa7, 0xd2, 0x26, 0xb9, 0x40,
	0xda, 0xb4, 0xb4, 0x23, 0x6d, 0x4a, 0x77, 0xc4, 0x99, 0xf3, 0xdd, 0xe7, 0x0a, 0x9d, 0x78, 0x2d,
	0x3a, 0x6c, 0xa5, 0x5f, 0x65, 0xa8, 0x89, 0xbf, 0xd2, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x29,
	0x32, 0x02, 0xa4, 0x3f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	CheckUserPassword(ctx context.Context, in *CheckUserPwdReq, opts ...grpc.CallOption) (*CheckUserPwdResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) CheckUserPassword(ctx context.Context, in *CheckUserPwdReq, opts ...grpc.CallOption) (*CheckUserPwdResp, error) {
	out := new(CheckUserPwdResp)
	err := c.cc.Invoke(ctx, "/user.User/CheckUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/user.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error) {
	out := new(RechargeResp)
	err := c.cc.Invoke(ctx, "/user.User/Recharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	CheckUserPassword(context.Context, *CheckUserPwdReq) (*CheckUserPwdResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Recharge(context.Context, *RechargeReq) (*RechargeResp, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) CheckUserPassword(ctx context.Context, req *CheckUserPwdReq) (*CheckUserPwdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserPassword not implemented")
}
func (*UnimplementedUserServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServer) Recharge(ctx context.Context, req *RechargeReq) (*RechargeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recharge not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CheckUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserPwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CheckUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckUserPassword(ctx, req.(*CheckUserPwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Recharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Recharge(ctx, req.(*RechargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUserPassword",
			Handler:    _User_CheckUserPassword_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Recharge",
			Handler:    _User_Recharge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic/user.proto",
}
