// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEMALE",
	2: "MALE",
}

var Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"FEMALE":  1,
	"MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18be7a49d0cb9194, []int{0}
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_18be7a49d0cb9194, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Balance              int64     `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Token                string    `protobuf:"bytes,100,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_18be7a49d0cb9194, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *LoginResp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=auth.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_18be7a49d0cb9194, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=auth.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_18be7a49d0cb9194, []int{3}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterResp struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_18be7a49d0cb9194, []int{4}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterEnum("auth.Gender", Gender_name, Gender_value)
	proto.RegisterType((*LoginReq)(nil), "auth.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "auth.LoginResp")
	proto.RegisterType((*UserInfo)(nil), "auth.UserInfo")
	proto.RegisterType((*RegisterReq)(nil), "auth.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "auth.RegisterResp")
}

func init() { proto.RegisterFile("logic/auth.proto", fileDescriptor_18be7a49d0cb9194) }

var fileDescriptor_18be7a49d0cb9194 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x5f, 0x4b, 0x3a, 0x41,
	0x14, 0x75, 0x75, 0x5d, 0xd7, 0xab, 0x3f, 0x7f, 0x7a, 0x0b, 0x5a, 0x7c, 0x92, 0x25, 0x48, 0x14,
	0x14, 0xf4, 0x0b, 0x64, 0x60, 0x11, 0x99, 0xc1, 0x80, 0x04, 0xbd, 0xc4, 0xba, 0x3b, 0xae, 0x8b,
	0x36, 0x33, 0xed, 0xec, 0xd2, 0x63, 0x4f, 0x7d, 0xef, 0x70, 0x76, 0x27, 0xad, 0xe8, 0x25, 0x7a,
	0xbb, 0xe7, 0x5e, 0xee, 0x39, 0xe7, 0xfe, 0x81, 0xe6, 0x96, 0x87, 0x91, 0x3f, 0xf4, 0xd2, 0x64,
	0x3d, 0x10, 0x31, 0x4f, 0x38, 0x9a, 0xbb, 0xd8, 0x3d, 0x07, 0x7b, 0xc6, 0xc3, 0x88, 0x11, 0xfa,
	0x8c, 0x0e, 0x54, 0x3c, 0xdf, 0xe7, 0x29, 0x4b, 0x1c, 0xa3, 0x63, 0x74, 0xab, 0x44, 0x43, 0x6c,
	0x83, 0x2d, 0x3c, 0x29, 0x5f, 0x78, 0x1c, 0x38, 0x45, 0x55, 0xfa, 0xc0, 0xee, 0x1a, 0xaa, 0x39,
	0x83, 0x14, 0xd8, 0x87, 0x6a, 0x2a, 0x69, 0xfc, 0x18, 0xb1, 0x15, 0x57, 0x24, 0xb5, 0x51, 0x63,
	0xa0, 0x44, 0x17, 0x92, 0xc6, 0xd7, 0x6c, 0xc5, 0x89, 0x9d, 0xe6, 0xd1, 0x4e, 0x6f, 0xe9, 0x6d,
	0x3d, 0xe6, 0x53, 0x45, 0x5a, 0x22, 0x1a, 0xe2, 0x31, 0x94, 0x13, 0xbe, 0xa1, 0xcc, 0x09, 0x94,
	0x58, 0x06, 0xdc, 0x57, 0xb0, 0x35, 0x0b, 0x9e, 0x40, 0x25, 0x13, 0x0a, 0x94, 0xcc, 0x3f, 0x62,
	0x29, 0xda, 0xe0, 0x70, 0x88, 0xe2, 0xb7, 0x21, 0x58, 0xe4, 0x6f, 0x98, 0xf7, 0x44, 0x9d, 0x52,
	0x36, 0x84, 0xc6, 0x78, 0x0a, 0x56, 0x48, 0x59, 0x40, 0x63, 0xc7, 0xec, 0x18, 0xdd, 0xc6, 0xa8,
	0x9e, 0x99, 0xbe, 0x52, 0x39, 0x92, 0xd7, 0xdc, 0x37, 0x03, 0x6a, 0x84, 0x86, 0x91, 0x4c, 0x68,
	0xfc, 0xeb, 0x85, 0xfd, 0x81, 0x8f, 0x33, 0xa8, 0xef, 0x6d, 0x48, 0xf1, 0xe3, 0x32, 0x7a, 0x7d,
	0xb0, 0xb2, 0x56, 0xac, 0x41, 0x65, 0x31, 0xbf, 0x99, 0xdf, 0xdd, 0xcf, 0x9b, 0x05, 0x04, 0xb0,
	0x2e, 0xa7, 0xb7, 0x93, 0xd9, 0xb4, 0x69, 0xa0, 0x0d, 0xa6, 0x8a, 0x8a, 0xa3, 0x10, 0xcc, 0x49,
	0x9a, 0xac, 0xb1, 0x07, 0x65, 0x75, 0x50, 0xcc, 0x2f, 0xa7, 0xff, 0xa3, 0xfd, 0xff, 0x13, 0x96,
	0xc2, 0x2d, 0xe0, 0x18, 0x6c, 0xed, 0x04, 0x5b, 0x59, 0xf9, 0x60, 0x41, 0x6d, 0xfc, 0x9a, 0xda,
	0x35, 0x5d, 0x1c, 0x3d, 0xb4, 0xc4, 0x26, 0x1c, 0x8a, 0xe5, 0x70, 0xff, 0x94, 0x4b, 0x4b, 0x7d,
	0xe5, 0xf8, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x41, 0xa0, 0xea, 0xa9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/auth.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/auth.Auth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic/auth.proto",
}
