// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/wallet/wallet.proto

package wallet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RechargeReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeReq) Reset()         { *m = RechargeReq{} }
func (m *RechargeReq) String() string { return proto.CompactTextString(m) }
func (*RechargeReq) ProtoMessage()    {}
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{0}
}

func (m *RechargeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeReq.Unmarshal(m, b)
}
func (m *RechargeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeReq.Marshal(b, m, deterministic)
}
func (m *RechargeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeReq.Merge(m, src)
}
func (m *RechargeReq) XXX_Size() int {
	return xxx_messageInfo_RechargeReq.Size(m)
}
func (m *RechargeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeReq proto.InternalMessageInfo

func (m *RechargeReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RechargeReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RechargeReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RechargeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeResp) Reset()         { *m = RechargeResp{} }
func (m *RechargeResp) String() string { return proto.CompactTextString(m) }
func (*RechargeResp) ProtoMessage()    {}
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{1}
}

func (m *RechargeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeResp.Unmarshal(m, b)
}
func (m *RechargeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeResp.Marshal(b, m, deterministic)
}
func (m *RechargeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeResp.Merge(m, src)
}
func (m *RechargeResp) XXX_Size() int {
	return xxx_messageInfo_RechargeResp.Size(m)
}
func (m *RechargeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeResp proto.InternalMessageInfo

type GetUserBalanceReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBalanceReq) Reset()         { *m = GetUserBalanceReq{} }
func (m *GetUserBalanceReq) String() string { return proto.CompactTextString(m) }
func (*GetUserBalanceReq) ProtoMessage()    {}
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{2}
}

func (m *GetUserBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBalanceReq.Unmarshal(m, b)
}
func (m *GetUserBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBalanceReq.Marshal(b, m, deterministic)
}
func (m *GetUserBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBalanceReq.Merge(m, src)
}
func (m *GetUserBalanceReq) XXX_Size() int {
	return xxx_messageInfo_GetUserBalanceReq.Size(m)
}
func (m *GetUserBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBalanceReq proto.InternalMessageInfo

func (m *GetUserBalanceReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserBalanceResp struct {
	Balance              int64    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBalanceResp) Reset()         { *m = GetUserBalanceResp{} }
func (m *GetUserBalanceResp) String() string { return proto.CompactTextString(m) }
func (*GetUserBalanceResp) ProtoMessage()    {}
func (*GetUserBalanceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{3}
}

func (m *GetUserBalanceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBalanceResp.Unmarshal(m, b)
}
func (m *GetUserBalanceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBalanceResp.Marshal(b, m, deterministic)
}
func (m *GetUserBalanceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBalanceResp.Merge(m, src)
}
func (m *GetUserBalanceResp) XXX_Size() int {
	return xxx_messageInfo_GetUserBalanceResp.Size(m)
}
func (m *GetUserBalanceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBalanceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBalanceResp proto.InternalMessageInfo

func (m *GetUserBalanceResp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetTopTenUserReq struct {
	Top                  uint32   `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopTenUserReq) Reset()         { *m = GetTopTenUserReq{} }
func (m *GetTopTenUserReq) String() string { return proto.CompactTextString(m) }
func (*GetTopTenUserReq) ProtoMessage()    {}
func (*GetTopTenUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{4}
}

func (m *GetTopTenUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopTenUserReq.Unmarshal(m, b)
}
func (m *GetTopTenUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopTenUserReq.Marshal(b, m, deterministic)
}
func (m *GetTopTenUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopTenUserReq.Merge(m, src)
}
func (m *GetTopTenUserReq) XXX_Size() int {
	return xxx_messageInfo_GetTopTenUserReq.Size(m)
}
func (m *GetTopTenUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopTenUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopTenUserReq proto.InternalMessageInfo

func (m *GetTopTenUserReq) GetTop() uint32 {
	if m != nil {
		return m.Top
	}
	return 0
}

type GetTopTenUserResp struct {
	UserList             string   `protobuf:"bytes,1,opt,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopTenUserResp) Reset()         { *m = GetTopTenUserResp{} }
func (m *GetTopTenUserResp) String() string { return proto.CompactTextString(m) }
func (*GetTopTenUserResp) ProtoMessage()    {}
func (*GetTopTenUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{5}
}

func (m *GetTopTenUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopTenUserResp.Unmarshal(m, b)
}
func (m *GetTopTenUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopTenUserResp.Marshal(b, m, deterministic)
}
func (m *GetTopTenUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopTenUserResp.Merge(m, src)
}
func (m *GetTopTenUserResp) XXX_Size() int {
	return xxx_messageInfo_GetTopTenUserResp.Size(m)
}
func (m *GetTopTenUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopTenUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopTenUserResp proto.InternalMessageInfo

func (m *GetTopTenUserResp) GetUserList() string {
	if m != nil {
		return m.UserList
	}
	return ""
}

type WriteNoPaidOrderReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteNoPaidOrderReq) Reset()         { *m = WriteNoPaidOrderReq{} }
func (m *WriteNoPaidOrderReq) String() string { return proto.CompactTextString(m) }
func (*WriteNoPaidOrderReq) ProtoMessage()    {}
func (*WriteNoPaidOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{6}
}

func (m *WriteNoPaidOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteNoPaidOrderReq.Unmarshal(m, b)
}
func (m *WriteNoPaidOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteNoPaidOrderReq.Marshal(b, m, deterministic)
}
func (m *WriteNoPaidOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteNoPaidOrderReq.Merge(m, src)
}
func (m *WriteNoPaidOrderReq) XXX_Size() int {
	return xxx_messageInfo_WriteNoPaidOrderReq.Size(m)
}
func (m *WriteNoPaidOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteNoPaidOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_WriteNoPaidOrderReq proto.InternalMessageInfo

func (m *WriteNoPaidOrderReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *WriteNoPaidOrderReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type WriteNoPaidOrderResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteNoPaidOrderResp) Reset()         { *m = WriteNoPaidOrderResp{} }
func (m *WriteNoPaidOrderResp) String() string { return proto.CompactTextString(m) }
func (*WriteNoPaidOrderResp) ProtoMessage()    {}
func (*WriteNoPaidOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{7}
}

func (m *WriteNoPaidOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteNoPaidOrderResp.Unmarshal(m, b)
}
func (m *WriteNoPaidOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteNoPaidOrderResp.Marshal(b, m, deterministic)
}
func (m *WriteNoPaidOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteNoPaidOrderResp.Merge(m, src)
}
func (m *WriteNoPaidOrderResp) XXX_Size() int {
	return xxx_messageInfo_WriteNoPaidOrderResp.Size(m)
}
func (m *WriteNoPaidOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteNoPaidOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_WriteNoPaidOrderResp proto.InternalMessageInfo

type PayReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayReq) Reset()         { *m = PayReq{} }
func (m *PayReq) String() string { return proto.CompactTextString(m) }
func (*PayReq) ProtoMessage()    {}
func (*PayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{8}
}

func (m *PayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayReq.Unmarshal(m, b)
}
func (m *PayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayReq.Marshal(b, m, deterministic)
}
func (m *PayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayReq.Merge(m, src)
}
func (m *PayReq) XXX_Size() int {
	return xxx_messageInfo_PayReq.Size(m)
}
func (m *PayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayReq proto.InternalMessageInfo

func (m *PayReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResp) Reset()         { *m = PayResp{} }
func (m *PayResp) String() string { return proto.CompactTextString(m) }
func (*PayResp) ProtoMessage()    {}
func (*PayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{9}
}

func (m *PayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResp.Unmarshal(m, b)
}
func (m *PayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResp.Marshal(b, m, deterministic)
}
func (m *PayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResp.Merge(m, src)
}
func (m *PayResp) XXX_Size() int {
	return xxx_messageInfo_PayResp.Size(m)
}
func (m *PayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RechargeReq)(nil), "wallet.RechargeReq")
	proto.RegisterType((*RechargeResp)(nil), "wallet.RechargeResp")
	proto.RegisterType((*GetUserBalanceReq)(nil), "wallet.GetUserBalanceReq")
	proto.RegisterType((*GetUserBalanceResp)(nil), "wallet.GetUserBalanceResp")
	proto.RegisterType((*GetTopTenUserReq)(nil), "wallet.GetTopTenUserReq")
	proto.RegisterType((*GetTopTenUserResp)(nil), "wallet.GetTopTenUserResp")
	proto.RegisterType((*WriteNoPaidOrderReq)(nil), "wallet.WriteNoPaidOrderReq")
	proto.RegisterType((*WriteNoPaidOrderResp)(nil), "wallet.WriteNoPaidOrderResp")
	proto.RegisterType((*PayReq)(nil), "wallet.PayReq")
	proto.RegisterType((*PayResp)(nil), "wallet.PayResp")
}

func init() { proto.RegisterFile("server/wallet/wallet.proto", fileDescriptor_6e585c95aeb2fa82) }

var fileDescriptor_6e585c95aeb2fa82 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x41, 0x8f, 0xda, 0x30,
	0x14, 0x84, 0x1b, 0x22, 0x25, 0xe4, 0xb5, 0x50, 0x6a, 0x50, 0x1a, 0xdc, 0x1e, 0x90, 0xd5, 0x43,
	0x0e, 0x15, 0x91, 0xda, 0x43, 0xef, 0x1c, 0x8a, 0x90, 0xaa, 0x82, 0x2c, 0x2a, 0xaa, 0x5e, 0x2a,
	0x93, 0x58, 0x34, 0x2a, 0x25, 0xae, 0x6d, 0x76, 0xc5, 0xaf, 0xdc, 0xbf, 0xb4, 0xb2, 0x93, 0xec,
	0x26, 0xb0, 0xec, 0x09, 0x26, 0xef, 0x7b, 0x63, 0x6b, 0x46, 0x06, 0xac, 0xb8, 0xbc, 0xe1, 0x32,
	0xb9, 0x65, 0xfb, 0x3d, 0xd7, 0xd5, 0xcf, 0x54, 0xc8, 0x42, 0x17, 0xc8, 0x2b, 0x15, 0xf9, 0x09,
	0x2f, 0x29, 0x4f, 0xff, 0x30, 0xb9, 0xe3, 0x94, 0xff, 0x47, 0x6f, 0xc1, 0x3f, 0x2a, 0x2e, 0x7f,
	0xe7, 0x59, 0xe4, 0x4c, 0x9c, 0xb8, 0x47, 0x3d, 0x23, 0x17, 0x19, 0x0a, 0xc1, 0x63, 0xff, 0x8a,
	0xe3, 0x41, 0x47, 0x9d, 0x89, 0x13, 0xbb, 0xb4, 0x52, 0x28, 0x02, 0x9f, 0xa5, 0xa9, 0x1d, 0xb8,
	0x13, 0x27, 0x0e, 0x68, 0x2d, 0x49, 0x1f, 0x5e, 0x3d, 0x3a, 0x2b, 0x41, 0x3e, 0xc2, 0x9b, 0x39,
	0xd7, 0x3f, 0x14, 0x97, 0x33, 0xb6, 0x67, 0x87, 0xf4, 0xd9, 0xf3, 0xc8, 0x14, 0xd0, 0x39, 0xad,
	0x84, 0x39, 0x6d, 0x5b, 0x4a, 0x8b, 0xbb, 0xb4, 0x96, 0xe4, 0x03, 0x0c, 0xe6, 0x5c, 0xaf, 0x0b,
	0xb1, 0xe6, 0x07, 0xb3, 0x65, 0xcc, 0x07, 0xe0, 0xea, 0x42, 0x54, 0xc6, 0xe6, 0x2f, 0x49, 0xec,
	0x1d, 0x9a, 0x94, 0x12, 0x08, 0x43, 0xd7, 0x1c, 0xfa, 0x2d, 0x57, 0xda, 0xb2, 0x01, 0x7d, 0xd0,
	0x64, 0x0e, 0xc3, 0x8d, 0xcc, 0x35, 0xff, 0x5e, 0xac, 0x58, 0x9e, 0x2d, 0x65, 0x56, 0x3a, 0x87,
	0x50, 0xdd, 0xf3, 0x2c, 0xa5, 0x08, 0xfc, 0xc2, 0x30, 0x8b, 0xcc, 0xc6, 0x14, 0xd0, 0x5a, 0x92,
	0x10, 0x46, 0x97, 0x46, 0x4a, 0x10, 0x02, 0xde, 0x8a, 0x9d, 0x8c, 0x67, 0x63, 0xd7, 0x69, 0xef,
	0x06, 0xe0, 0x5b, 0x46, 0x89, 0x4f, 0x77, 0x1d, 0xf0, 0x36, 0xb6, 0x39, 0xf4, 0x05, 0xba, 0x75,
	0xbe, 0x68, 0x38, 0xad, 0xca, 0x6d, 0x74, 0x89, 0x47, 0x97, 0x1f, 0x95, 0x20, 0x2f, 0xd0, 0x02,
	0xfa, 0xed, 0x68, 0xd1, 0xb8, 0x26, 0x2f, 0x0a, 0xc2, 0xf8, 0xda, 0xc8, 0x5a, 0x7d, 0x85, 0x5e,
	0x2b, 0x4f, 0x14, 0x35, 0xf0, 0x56, 0x19, 0x78, 0x7c, 0x65, 0x62, 0x7d, 0x96, 0x30, 0x38, 0x4f,
	0x07, 0xbd, 0xab, 0x17, 0x9e, 0x28, 0x00, 0xbf, 0xbf, 0x3e, 0xb4, 0x86, 0x31, 0xb8, 0x2b, 0x76,
	0x42, 0xfd, 0x1a, 0x2b, 0x33, 0xc6, 0xaf, 0x5b, 0xda, 0x90, 0xb3, 0xf0, 0xd7, 0x48, 0xfc, 0xdd,
	0x25, 0x62, 0x9b, 0xb4, 0x5e, 0xcb, 0xd6, 0xb3, 0xef, 0xe4, 0xf3, 0x7d, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xb5, 0x47, 0x10, 0x45, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error)
	GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceResp, error)
	GetTopTenUser(ctx context.Context, in *GetTopTenUserReq, opts ...grpc.CallOption) (*GetTopTenUserResp, error)
	WriteNoPaidOrder(ctx context.Context, in *WriteNoPaidOrderReq, opts ...grpc.CallOption) (*WriteNoPaidOrderResp, error)
	Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error) {
	out := new(RechargeResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/Recharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceResp, error) {
	out := new(GetUserBalanceResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/GetUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetTopTenUser(ctx context.Context, in *GetTopTenUserReq, opts ...grpc.CallOption) (*GetTopTenUserResp, error) {
	out := new(GetTopTenUserResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/GetTopTenUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WriteNoPaidOrder(ctx context.Context, in *WriteNoPaidOrderReq, opts ...grpc.CallOption) (*WriteNoPaidOrderResp, error) {
	out := new(WriteNoPaidOrderResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/WriteNoPaidOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	out := new(PayResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	Recharge(context.Context, *RechargeReq) (*RechargeResp, error)
	GetUserBalance(context.Context, *GetUserBalanceReq) (*GetUserBalanceResp, error)
	GetTopTenUser(context.Context, *GetTopTenUserReq) (*GetTopTenUserResp, error)
	WriteNoPaidOrder(context.Context, *WriteNoPaidOrderReq) (*WriteNoPaidOrderResp, error)
	Pay(context.Context, *PayReq) (*PayResp, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) Recharge(ctx context.Context, req *RechargeReq) (*RechargeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recharge not implemented")
}
func (*UnimplementedWalletServer) GetUserBalance(ctx context.Context, req *GetUserBalanceReq) (*GetUserBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalance not implemented")
}
func (*UnimplementedWalletServer) GetTopTenUser(ctx context.Context, req *GetTopTenUserReq) (*GetTopTenUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopTenUser not implemented")
}
func (*UnimplementedWalletServer) WriteNoPaidOrder(ctx context.Context, req *WriteNoPaidOrderReq) (*WriteNoPaidOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteNoPaidOrder not implemented")
}
func (*UnimplementedWalletServer) Pay(ctx context.Context, req *PayReq) (*PayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/Recharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Recharge(ctx, req.(*RechargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/GetUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetUserBalance(ctx, req.(*GetUserBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetTopTenUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopTenUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetTopTenUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/GetTopTenUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetTopTenUser(ctx, req.(*GetTopTenUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WriteNoPaidOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteNoPaidOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).WriteNoPaidOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/WriteNoPaidOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).WriteNoPaidOrder(ctx, req.(*WriteNoPaidOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Pay(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recharge",
			Handler:    _Wallet_Recharge_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _Wallet_GetUserBalance_Handler,
		},
		{
			MethodName: "GetTopTenUser",
			Handler:    _Wallet_GetTopTenUser_Handler,
		},
		{
			MethodName: "WriteNoPaidOrder",
			Handler:    _Wallet_WriteNoPaidOrder_Handler,
		},
		{
			MethodName: "Pay",
			Handler:    _Wallet_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/wallet/wallet.proto",
}
