// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/wallet/wallet.proto

package wallet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RechargeReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeReq) Reset()         { *m = RechargeReq{} }
func (m *RechargeReq) String() string { return proto.CompactTextString(m) }
func (*RechargeReq) ProtoMessage()    {}
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{0}
}

func (m *RechargeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeReq.Unmarshal(m, b)
}
func (m *RechargeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeReq.Marshal(b, m, deterministic)
}
func (m *RechargeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeReq.Merge(m, src)
}
func (m *RechargeReq) XXX_Size() int {
	return xxx_messageInfo_RechargeReq.Size(m)
}
func (m *RechargeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeReq proto.InternalMessageInfo

func (m *RechargeReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RechargeReq) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RechargeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeResp) Reset()         { *m = RechargeResp{} }
func (m *RechargeResp) String() string { return proto.CompactTextString(m) }
func (*RechargeResp) ProtoMessage()    {}
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{1}
}

func (m *RechargeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeResp.Unmarshal(m, b)
}
func (m *RechargeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeResp.Marshal(b, m, deterministic)
}
func (m *RechargeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeResp.Merge(m, src)
}
func (m *RechargeResp) XXX_Size() int {
	return xxx_messageInfo_RechargeResp.Size(m)
}
func (m *RechargeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeResp proto.InternalMessageInfo

type GetUserBalanceReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBalanceReq) Reset()         { *m = GetUserBalanceReq{} }
func (m *GetUserBalanceReq) String() string { return proto.CompactTextString(m) }
func (*GetUserBalanceReq) ProtoMessage()    {}
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{2}
}

func (m *GetUserBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBalanceReq.Unmarshal(m, b)
}
func (m *GetUserBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBalanceReq.Marshal(b, m, deterministic)
}
func (m *GetUserBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBalanceReq.Merge(m, src)
}
func (m *GetUserBalanceReq) XXX_Size() int {
	return xxx_messageInfo_GetUserBalanceReq.Size(m)
}
func (m *GetUserBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBalanceReq proto.InternalMessageInfo

func (m *GetUserBalanceReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserBalanceResp struct {
	Balance              uint64   `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBalanceResp) Reset()         { *m = GetUserBalanceResp{} }
func (m *GetUserBalanceResp) String() string { return proto.CompactTextString(m) }
func (*GetUserBalanceResp) ProtoMessage()    {}
func (*GetUserBalanceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e585c95aeb2fa82, []int{3}
}

func (m *GetUserBalanceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBalanceResp.Unmarshal(m, b)
}
func (m *GetUserBalanceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBalanceResp.Marshal(b, m, deterministic)
}
func (m *GetUserBalanceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBalanceResp.Merge(m, src)
}
func (m *GetUserBalanceResp) XXX_Size() int {
	return xxx_messageInfo_GetUserBalanceResp.Size(m)
}
func (m *GetUserBalanceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBalanceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBalanceResp proto.InternalMessageInfo

func (m *GetUserBalanceResp) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*RechargeReq)(nil), "wallet.RechargeReq")
	proto.RegisterType((*RechargeResp)(nil), "wallet.RechargeResp")
	proto.RegisterType((*GetUserBalanceReq)(nil), "wallet.GetUserBalanceReq")
	proto.RegisterType((*GetUserBalanceResp)(nil), "wallet.GetUserBalanceResp")
}

func init() { proto.RegisterFile("server/wallet/wallet.proto", fileDescriptor_6e585c95aeb2fa82) }

var fileDescriptor_6e585c95aeb2fa82 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0x81, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92, 0x0d, 0x17, 0x77, 0x50, 0x6a, 0x72, 0x46, 0x62, 0x51, 0x7a,
	0x6a, 0x50, 0x6a, 0xa1, 0x90, 0x38, 0x17, 0x7b, 0x69, 0x71, 0x6a, 0x51, 0x7c, 0x66, 0x8a, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x1b, 0x88, 0xeb, 0x99, 0x22, 0x24, 0xc2, 0xc5, 0x9a, 0x9c,
	0x5f, 0x9a, 0x57, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0xe1, 0x28, 0xf1, 0x71, 0xf1,
	0x20, 0x74, 0x17, 0x17, 0x28, 0xe9, 0x70, 0x09, 0xba, 0xa7, 0x96, 0x84, 0x16, 0xa7, 0x16, 0x39,
	0x25, 0xe6, 0x24, 0xe6, 0x25, 0xe3, 0x35, 0x53, 0x49, 0x8f, 0x4b, 0x08, 0x5d, 0x75, 0x71, 0x81,
	0x90, 0x04, 0x17, 0x7b, 0x12, 0x84, 0x0b, 0x56, 0xce, 0x12, 0x04, 0xe3, 0x1a, 0xf5, 0x30, 0x72,
	0xb1, 0x85, 0x83, 0x9d, 0x2d, 0x64, 0xce, 0xc5, 0x01, 0xb3, 0x58, 0x48, 0x58, 0x0f, 0xea, 0x33,
	0x24, 0x8f, 0x48, 0x89, 0x60, 0x0a, 0x16, 0x17, 0x28, 0x31, 0x08, 0x79, 0x72, 0xf1, 0xa1, 0xda,
	0x29, 0x24, 0x09, 0x53, 0x89, 0xe1, 0x72, 0x29, 0x29, 0x5c, 0x52, 0x20, 0xa3, 0x9c, 0xc4, 0xa2,
	0x44, 0x0a, 0xb2, 0xd3, 0xf5, 0x0b, 0x92, 0xf4, 0x51, 0xc2, 0x39, 0x89, 0x0d, 0x1c, 0xc2, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x76, 0x55, 0xb0, 0x7f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error)
	GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceResp, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error) {
	out := new(RechargeResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/Recharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceResp, error) {
	out := new(GetUserBalanceResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/GetUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	Recharge(context.Context, *RechargeReq) (*RechargeResp, error)
	GetUserBalance(context.Context, *GetUserBalanceReq) (*GetUserBalanceResp, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) Recharge(ctx context.Context, req *RechargeReq) (*RechargeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recharge not implemented")
}
func (*UnimplementedWalletServer) GetUserBalance(ctx context.Context, req *GetUserBalanceReq) (*GetUserBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalance not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/Recharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Recharge(ctx, req.(*RechargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/GetUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetUserBalance(ctx, req.(*GetUserBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recharge",
			Handler:    _Wallet_Recharge_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _Wallet_GetUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/wallet/wallet.proto",
}
