// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/pay/consume.proto

package consume

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeReq struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ItemNum              int64    `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeReq) Reset()         { *m = ConsumeReq{} }
func (m *ConsumeReq) String() string { return proto.CompactTextString(m) }
func (*ConsumeReq) ProtoMessage()    {}
func (*ConsumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_860d4fe251d47ca1, []int{0}
}

func (m *ConsumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeReq.Unmarshal(m, b)
}
func (m *ConsumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeReq.Marshal(b, m, deterministic)
}
func (m *ConsumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeReq.Merge(m, src)
}
func (m *ConsumeReq) XXX_Size() int {
	return xxx_messageInfo_ConsumeReq.Size(m)
}
func (m *ConsumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeReq proto.InternalMessageInfo

func (m *ConsumeReq) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ConsumeReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ConsumeReq) GetItemNum() int64 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *ConsumeReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ConsumeResp struct {
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeResp) Reset()         { *m = ConsumeResp{} }
func (m *ConsumeResp) String() string { return proto.CompactTextString(m) }
func (*ConsumeResp) ProtoMessage()    {}
func (*ConsumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_860d4fe251d47ca1, []int{1}
}

func (m *ConsumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResp.Unmarshal(m, b)
}
func (m *ConsumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResp.Marshal(b, m, deterministic)
}
func (m *ConsumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResp.Merge(m, src)
}
func (m *ConsumeResp) XXX_Size() int {
	return xxx_messageInfo_ConsumeResp.Size(m)
}
func (m *ConsumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResp proto.InternalMessageInfo

func (m *ConsumeResp) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func init() {
	proto.RegisterType((*ConsumeReq)(nil), "consume.ConsumeReq")
	proto.RegisterType((*ConsumeResp)(nil), "consume.ConsumeResp")
}

func init() { proto.RegisterFile("server/pay/consume.proto", fileDescriptor_860d4fe251d47ca1) }

var fileDescriptor_860d4fe251d47ca1 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x4f, 0xc4, 0x20,
	0x18, 0x86, 0xe5, 0xaa, 0xad, 0x7e, 0xb7, 0xa1, 0xe6, 0xd0, 0x89, 0x74, 0x62, 0x3a, 0x92, 0x73,
	0x76, 0xd1, 0xa9, 0x8b, 0x31, 0x8c, 0x2e, 0xa6, 0x2d, 0xc4, 0x10, 0x43, 0x41, 0x28, 0x26, 0x8d,
	0xff, 0xbc, 0x81, 0xe2, 0x8f, 0xe4, 0x36, 0x9e, 0x2f, 0xef, 0xf7, 0x00, 0x2f, 0x90, 0xa0, 0xfc,
	0xa7, 0xf2, 0xdc, 0xf5, 0x0b, 0x1f, 0xed, 0x14, 0xa2, 0x51, 0x7b, 0xe7, 0xed, 0x6c, 0x71, 0x53,
	0xb0, 0xfd, 0x02, 0x78, 0x5c, 0x8f, 0x42, 0x7d, 0xe0, 0x1d, 0x34, 0x7a, 0x56, 0xe6, 0x55, 0x4b,
	0x82, 0x28, 0x62, 0x95, 0xa8, 0x13, 0x76, 0x12, 0x53, 0xd8, 0x4a, 0x15, 0x46, 0xaf, 0xdd, 0xac,
	0xed, 0x44, 0x36, 0x14, 0xb1, 0x0b, 0xf1, 0x7f, 0x84, 0x6f, 0xe0, 0x3c, 0xaf, 0x4e, 0xd1, 0x90,
	0x2a, 0xef, 0x66, 0xd5, 0x53, 0x34, 0xc9, 0x1a, 0x83, 0xf2, 0xc9, 0x7a, 0x4a, 0x11, 0x3b, 0x13,
	0x75, 0xc2, 0x4e, 0xb6, 0x0c, 0xb6, 0xbf, 0x97, 0x07, 0x97, 0x14, 0xd6, 0xcb, 0x35, 0xb8, 0x59,
	0x15, 0x99, 0x3b, 0x79, 0xb8, 0x87, 0xa6, 0x24, 0xf1, 0x01, 0xaa, 0xe7, 0x7e, 0xc1, 0x97, 0xfb,
	0x9f, 0x1f, 0xfd, 0xbd, 0xff, 0xf6, 0xea, 0x78, 0x18, 0x5c, 0x7b, 0xf2, 0xb0, 0x7b, 0xb9, 0x76,
	0xef, 0x6f, 0xdc, 0x0d, 0xbc, 0x34, 0x52, 0x62, 0x43, 0x9d, 0xeb, 0xb8, 0xfb, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x52, 0xb1, 0xe9, 0x2a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsumeClient is the client API for Consume service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumeClient interface {
	Pay(ctx context.Context, in *ConsumeReq, opts ...grpc.CallOption) (*ConsumeResp, error)
}

type consumeClient struct {
	cc *grpc.ClientConn
}

func NewConsumeClient(cc *grpc.ClientConn) ConsumeClient {
	return &consumeClient{cc}
}

func (c *consumeClient) Pay(ctx context.Context, in *ConsumeReq, opts ...grpc.CallOption) (*ConsumeResp, error) {
	out := new(ConsumeResp)
	err := c.cc.Invoke(ctx, "/consume.Consume/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumeServer is the server API for Consume service.
type ConsumeServer interface {
	Pay(context.Context, *ConsumeReq) (*ConsumeResp, error)
}

// UnimplementedConsumeServer can be embedded to have forward compatible implementations.
type UnimplementedConsumeServer struct {
}

func (*UnimplementedConsumeServer) Pay(ctx context.Context, req *ConsumeReq) (*ConsumeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterConsumeServer(s *grpc.Server, srv ConsumeServer) {
	s.RegisterService(&_Consume_serviceDesc, srv)
}

func _Consume_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumeServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consume.Consume/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumeServer).Pay(ctx, req.(*ConsumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Consume_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consume.Consume",
	HandlerType: (*ConsumeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pay",
			Handler:    _Consume_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/pay/consume.proto",
}
