// Code generated by protoc-gen-go. DO NOT EDIT.
// source: field.proto

package field

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeReq struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ItemNum              int64    `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeReq) Reset()         { *m = ConsumeReq{} }
func (m *ConsumeReq) String() string { return proto.CompactTextString(m) }
func (*ConsumeReq) ProtoMessage()    {}
func (*ConsumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_04234ff7fdd53e6e, []int{0}
}

func (m *ConsumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeReq.Unmarshal(m, b)
}
func (m *ConsumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeReq.Marshal(b, m, deterministic)
}
func (m *ConsumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeReq.Merge(m, src)
}
func (m *ConsumeReq) XXX_Size() int {
	return xxx_messageInfo_ConsumeReq.Size(m)
}
func (m *ConsumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeReq proto.InternalMessageInfo

func (m *ConsumeReq) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ConsumeReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ConsumeReq) GetItemNum() int64 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *ConsumeReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ConsumeResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeResp) Reset()         { *m = ConsumeResp{} }
func (m *ConsumeResp) String() string { return proto.CompactTextString(m) }
func (*ConsumeResp) ProtoMessage()    {}
func (*ConsumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_04234ff7fdd53e6e, []int{1}
}

func (m *ConsumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResp.Unmarshal(m, b)
}
func (m *ConsumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResp.Marshal(b, m, deterministic)
}
func (m *ConsumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResp.Merge(m, src)
}
func (m *ConsumeResp) XXX_Size() int {
	return xxx_messageInfo_ConsumeResp.Size(m)
}
func (m *ConsumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResp proto.InternalMessageInfo

func (m *ConsumeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConsumeResp) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func init() {
	proto.RegisterType((*ConsumeReq)(nil), "field.ConsumeReq")
	proto.RegisterType((*ConsumeResp)(nil), "field.ConsumeResp")
}

func init() { proto.RegisterFile("field.proto", fileDescriptor_04234ff7fdd53e6e) }

var fileDescriptor_04234ff7fdd53e6e = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbb, 0x4e, 0xc4, 0x30,
	0x10, 0x45, 0xf1, 0x86, 0x4d, 0xd8, 0x49, 0xc5, 0x34, 0x18, 0x2a, 0x2b, 0x55, 0xaa, 0x14, 0x50,
	0xd1, 0xb2, 0x55, 0x1a, 0x84, 0xfc, 0x03, 0x28, 0xe0, 0x01, 0x59, 0x8a, 0x1f, 0xf8, 0x51, 0x20,
	0x7e, 0x1e, 0xd9, 0x11, 0x0f, 0x6d, 0x79, 0x46, 0xba, 0xe7, 0xea, 0x0e, 0xf4, 0x6f, 0x9a, 0x56,
	0x35, 0xf9, 0xe0, 0x92, 0xc3, 0x7d, 0x85, 0xe1, 0x0b, 0xe0, 0xe8, 0x6c, 0xcc, 0x86, 0x24, 0x7d,
	0xe0, 0x15, 0x74, 0x3a, 0x91, 0x79, 0xd6, 0x8a, 0x33, 0xc1, 0xc6, 0x46, 0xb6, 0x05, 0x67, 0x85,
	0x02, 0x7a, 0x45, 0xf1, 0x35, 0x68, 0x9f, 0xb4, 0xb3, 0x7c, 0x27, 0xd8, 0x78, 0x90, 0xff, 0x4f,
	0x78, 0x0d, 0x17, 0x35, 0x6a, 0xb3, 0xe1, 0x4d, 0xcd, 0x56, 0xd5, 0x63, 0x36, 0xc5, 0x9a, 0x23,
	0x85, 0x62, 0x3d, 0x17, 0x6c, 0xdc, 0xcb, 0xb6, 0xe0, 0xac, 0x86, 0x07, 0xe8, 0x7f, 0xcb, 0xa3,
	0x47, 0x0e, 0x9d, 0xa1, 0x18, 0x97, 0x77, 0xaa, 0xed, 0x07, 0xf9, 0x83, 0x45, 0xee, 0x82, 0xda,
	0x14, 0xbb, 0x4d, 0x5e, 0x79, 0x56, 0xb7, 0xf7, 0xd0, 0x1d, 0x9d, 0x4d, 0xc1, 0xad, 0x38, 0x41,
	0xf3, 0xb4, 0x7c, 0xe2, 0xe5, 0xb4, 0xed, 0xfc, 0xdb, 0x75, 0x83, 0xa7, 0xa7, 0xe8, 0x87, 0xb3,
	0x97, 0xb6, 0x7e, 0xe2, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x28, 0x4f, 0xac, 0xe0, 0x18, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	Pay(ctx context.Context, in *ConsumeReq, opts ...grpc.CallOption) (*ConsumeResp, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Pay(ctx context.Context, in *ConsumeReq, opts ...grpc.CallOption) (*ConsumeResp, error) {
	out := new(ConsumeResp)
	err := c.cc.Invoke(ctx, "/field.Control/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	Pay(context.Context, *ConsumeReq) (*ConsumeResp, error)
}

// UnimplementedControlServer can be embedded to have forward compatible implementations.
type UnimplementedControlServer struct {
}

func (*UnimplementedControlServer) Pay(ctx context.Context, req *ConsumeReq) (*ConsumeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/field.Control/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Pay(ctx, req.(*ConsumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "field.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pay",
			Handler:    _Control_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "field.proto",
}
