// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Field.proto

package Field

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeReq struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ItemNum              int64    `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeReq) Reset()         { *m = ConsumeReq{} }
func (m *ConsumeReq) String() string { return proto.CompactTextString(m) }
func (*ConsumeReq) ProtoMessage()    {}
func (*ConsumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{0}
}

func (m *ConsumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeReq.Unmarshal(m, b)
}
func (m *ConsumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeReq.Marshal(b, m, deterministic)
}
func (m *ConsumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeReq.Merge(m, src)
}
func (m *ConsumeReq) XXX_Size() int {
	return xxx_messageInfo_ConsumeReq.Size(m)
}
func (m *ConsumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeReq proto.InternalMessageInfo

func (m *ConsumeReq) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ConsumeReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ConsumeReq) GetItemNum() int64 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *ConsumeReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ConsumeResp struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeResp) Reset()         { *m = ConsumeResp{} }
func (m *ConsumeResp) String() string { return proto.CompactTextString(m) }
func (*ConsumeResp) ProtoMessage()    {}
func (*ConsumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{1}
}

func (m *ConsumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResp.Unmarshal(m, b)
}
func (m *ConsumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResp.Marshal(b, m, deterministic)
}
func (m *ConsumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResp.Merge(m, src)
}
func (m *ConsumeResp) XXX_Size() int {
	return xxx_messageInfo_ConsumeResp.Size(m)
}
func (m *ConsumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResp proto.InternalMessageInfo

func (m *ConsumeResp) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ConsumeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConsumeResp) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type QueryReq struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{2}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type QueryResp struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{3}
}

func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (m *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(m, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

func (m *QueryResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *QueryResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ReturnReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnReq) Reset()         { *m = ReturnReq{} }
func (m *ReturnReq) String() string { return proto.CompactTextString(m) }
func (*ReturnReq) ProtoMessage()    {}
func (*ReturnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{4}
}

func (m *ReturnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnReq.Unmarshal(m, b)
}
func (m *ReturnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnReq.Marshal(b, m, deterministic)
}
func (m *ReturnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnReq.Merge(m, src)
}
func (m *ReturnReq) XXX_Size() int {
	return xxx_messageInfo_ReturnReq.Size(m)
}
func (m *ReturnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnReq proto.InternalMessageInfo

func (m *ReturnReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ReturnReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ReturnResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	OrderIdRet           string   `protobuf:"bytes,2,opt,name=order_id_ret,json=orderIdRet,proto3" json:"order_id_ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnResp) Reset()         { *m = ReturnResp{} }
func (m *ReturnResp) String() string { return proto.CompactTextString(m) }
func (*ReturnResp) ProtoMessage()    {}
func (*ReturnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{5}
}

func (m *ReturnResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnResp.Unmarshal(m, b)
}
func (m *ReturnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnResp.Marshal(b, m, deterministic)
}
func (m *ReturnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnResp.Merge(m, src)
}
func (m *ReturnResp) XXX_Size() int {
	return xxx_messageInfo_ReturnResp.Size(m)
}
func (m *ReturnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnResp proto.InternalMessageInfo

func (m *ReturnResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ReturnResp) GetOrderIdRet() string {
	if m != nil {
		return m.OrderIdRet
	}
	return ""
}

type RegisteredReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CallNum              string   `protobuf:"bytes,3,opt,name=call_num,json=callNum,proto3" json:"call_num,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday             int32    `protobuf:"varint,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredReq) Reset()         { *m = RegisteredReq{} }
func (m *RegisteredReq) String() string { return proto.CompactTextString(m) }
func (*RegisteredReq) ProtoMessage()    {}
func (*RegisteredReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{6}
}

func (m *RegisteredReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredReq.Unmarshal(m, b)
}
func (m *RegisteredReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredReq.Marshal(b, m, deterministic)
}
func (m *RegisteredReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredReq.Merge(m, src)
}
func (m *RegisteredReq) XXX_Size() int {
	return xxx_messageInfo_RegisteredReq.Size(m)
}
func (m *RegisteredReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredReq proto.InternalMessageInfo

func (m *RegisteredReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisteredReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *RegisteredReq) GetCallNum() string {
	if m != nil {
		return m.CallNum
	}
	return ""
}

func (m *RegisteredReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *RegisteredReq) GetBirthday() int32 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

type RegisteredResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Account              int64    `protobuf:"varint,2,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CallNum              int32    `protobuf:"varint,4,opt,name=call_num,json=callNum,proto3" json:"call_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredResp) Reset()         { *m = RegisteredResp{} }
func (m *RegisteredResp) String() string { return proto.CompactTextString(m) }
func (*RegisteredResp) ProtoMessage()    {}
func (*RegisteredResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{7}
}

func (m *RegisteredResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredResp.Unmarshal(m, b)
}
func (m *RegisteredResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredResp.Marshal(b, m, deterministic)
}
func (m *RegisteredResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredResp.Merge(m, src)
}
func (m *RegisteredResp) XXX_Size() int {
	return xxx_messageInfo_RegisteredResp.Size(m)
}
func (m *RegisteredResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredResp proto.InternalMessageInfo

func (m *RegisteredResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *RegisteredResp) GetAccount() int64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *RegisteredResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisteredResp) GetCallNum() int32 {
	if m != nil {
		return m.CallNum
	}
	return 0
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{8}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type LoginResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{9}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RechargeReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Money                int32    `protobuf:"varint,3,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeReq) Reset()         { *m = RechargeReq{} }
func (m *RechargeReq) String() string { return proto.CompactTextString(m) }
func (*RechargeReq) ProtoMessage()    {}
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{10}
}

func (m *RechargeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeReq.Unmarshal(m, b)
}
func (m *RechargeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeReq.Marshal(b, m, deterministic)
}
func (m *RechargeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeReq.Merge(m, src)
}
func (m *RechargeReq) XXX_Size() int {
	return xxx_messageInfo_RechargeReq.Size(m)
}
func (m *RechargeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeReq proto.InternalMessageInfo

func (m *RechargeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RechargeReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *RechargeReq) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

type RechargeResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeResp) Reset()         { *m = RechargeResp{} }
func (m *RechargeResp) String() string { return proto.CompactTextString(m) }
func (*RechargeResp) ProtoMessage()    {}
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{11}
}

func (m *RechargeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeResp.Unmarshal(m, b)
}
func (m *RechargeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeResp.Marshal(b, m, deterministic)
}
func (m *RechargeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeResp.Merge(m, src)
}
func (m *RechargeResp) XXX_Size() int {
	return xxx_messageInfo_RechargeResp.Size(m)
}
func (m *RechargeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeResp proto.InternalMessageInfo

func (m *RechargeResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type OrderReq struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderReq) Reset()         { *m = OrderReq{} }
func (m *OrderReq) String() string { return proto.CompactTextString(m) }
func (*OrderReq) ProtoMessage()    {}
func (*OrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{12}
}

func (m *OrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderReq.Unmarshal(m, b)
}
func (m *OrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderReq.Marshal(b, m, deterministic)
}
func (m *OrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderReq.Merge(m, src)
}
func (m *OrderReq) XXX_Size() int {
	return xxx_messageInfo_OrderReq.Size(m)
}
func (m *OrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_OrderReq proto.InternalMessageInfo

func (m *OrderReq) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *OrderReq) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type OrderResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResp) Reset()         { *m = OrderResp{} }
func (m *OrderResp) String() string { return proto.CompactTextString(m) }
func (*OrderResp) ProtoMessage()    {}
func (*OrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e63749c35df299, []int{13}
}

func (m *OrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResp.Unmarshal(m, b)
}
func (m *OrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResp.Marshal(b, m, deterministic)
}
func (m *OrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResp.Merge(m, src)
}
func (m *OrderResp) XXX_Size() int {
	return xxx_messageInfo_OrderResp.Size(m)
}
func (m *OrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResp proto.InternalMessageInfo

func (m *OrderResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ConsumeReq)(nil), "Field.ConsumeReq")
	proto.RegisterType((*ConsumeResp)(nil), "Field.ConsumeResp")
	proto.RegisterType((*QueryReq)(nil), "Field.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "Field.QueryResp")
	proto.RegisterType((*ReturnReq)(nil), "Field.ReturnReq")
	proto.RegisterType((*ReturnResp)(nil), "Field.ReturnResp")
	proto.RegisterType((*RegisteredReq)(nil), "Field.RegisteredReq")
	proto.RegisterType((*RegisteredResp)(nil), "Field.RegisteredResp")
	proto.RegisterType((*LoginReq)(nil), "Field.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "Field.LoginResp")
	proto.RegisterType((*RechargeReq)(nil), "Field.RechargeReq")
	proto.RegisterType((*RechargeResp)(nil), "Field.RechargeResp")
	proto.RegisterType((*OrderReq)(nil), "Field.OrderReq")
	proto.RegisterType((*OrderResp)(nil), "Field.OrderResp")
}

func init() { proto.RegisterFile("Field.proto", fileDescriptor_02e63749c35df299) }

var fileDescriptor_02e63749c35df299 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0xda, 0xb1, 0x27, 0xa5, 0xd0, 0xa5, 0x04, 0xe3, 0x53, 0xe4, 0x4a, 0x28, 0x42,
	0xd0, 0x03, 0x3d, 0x80, 0x84, 0x10, 0x07, 0xaa, 0x4a, 0x91, 0x10, 0xd0, 0xe5, 0xc6, 0xa5, 0x72,
	0xb3, 0xa3, 0xd4, 0x22, 0xfe, 0xe9, 0xae, 0x0d, 0x8a, 0x78, 0x05, 0x5e, 0x8f, 0xf7, 0x41, 0xfb,
	0x1b, 0xa7, 0x4d, 0x8b, 0x7a, 0xcb, 0x37, 0x9b, 0xfd, 0x7e, 0x66, 0x66, 0x0d, 0xa3, 0xd3, 0x02,
	0x97, 0xec, 0xa8, 0xe1, 0x75, 0x5b, 0x93, 0x40, 0x81, 0xec, 0x37, 0xc0, 0xc7, 0xba, 0x12, 0x5d,
	0x89, 0x14, 0xaf, 0xc8, 0x53, 0x18, 0x16, 0x2d, 0x96, 0xe7, 0x05, 0x4b, 0xbc, 0x89, 0x37, 0xf5,
	0x69, 0x28, 0xe1, 0x8c, 0x91, 0x09, 0x8c, 0x18, 0x8a, 0x39, 0x2f, 0x9a, 0xb6, 0xa8, 0xab, 0x64,
	0x30, 0xf1, 0xa6, 0x31, 0xed, 0x97, 0xc8, 0x33, 0x88, 0xd4, 0xd5, 0xaa, 0x2b, 0x13, 0x5f, 0xdd,
	0x55, 0x54, 0x9f, 0xbb, 0x52, 0xb2, 0x76, 0x02, 0xb9, 0x64, 0xdd, 0x99, 0x78, 0xd3, 0x80, 0x86,
	0x12, 0xce, 0x58, 0xf6, 0x1d, 0x46, 0x4e, 0x5c, 0x34, 0x64, 0x0c, 0x21, 0x47, 0xd1, 0x2d, 0x5b,
	0x2b, 0xae, 0x11, 0x49, 0x60, 0x58, 0xa2, 0x10, 0xf9, 0x02, 0x8d, 0xb0, 0x85, 0x52, 0xb4, 0xe6,
	0x4c, 0x53, 0xfb, 0xfa, 0x48, 0xe1, 0x19, 0xcb, 0x0e, 0x21, 0x3a, 0xeb, 0x90, 0xaf, 0xb6, 0xc4,
	0x8a, 0x6d, 0xac, 0xec, 0x3d, 0xc4, 0xe6, 0x4f, 0xa2, 0x21, 0x7b, 0x30, 0x98, 0x9d, 0x18, 0xe9,
	0xc1, 0xec, 0xe4, 0xff, 0x99, 0xb3, 0x0f, 0x10, 0x53, 0x6c, 0x3b, 0x5e, 0x49, 0x91, 0xbe, 0x17,
	0x6f, 0xc3, 0x4b, 0xbf, 0x01, 0x83, 0x8d, 0x06, 0x9c, 0x02, 0x58, 0x82, 0x1b, 0xf9, 0x63, 0x97,
	0x7f, 0x02, 0xbb, 0x96, 0xf9, 0x9c, 0x63, 0x6b, 0x9c, 0x80, 0x61, 0xa7, 0xd8, 0x66, 0x7f, 0x3c,
	0x78, 0x40, 0x71, 0x51, 0x88, 0x16, 0x39, 0x32, 0xe9, 0x86, 0xc0, 0x4e, 0x95, 0x97, 0x68, 0x98,
	0xd4, 0x6f, 0xd9, 0xc7, 0x1f, 0xb8, 0xfa, 0x55, 0x73, 0x66, 0xfb, 0x68, 0xa0, 0xf4, 0x3e, 0xcf,
	0x97, 0x4b, 0x37, 0xbc, 0x98, 0x0e, 0x25, 0x96, 0xc3, 0x1b, 0x43, 0xb8, 0xc0, 0x8a, 0x21, 0x57,
	0xb3, 0x8b, 0xa9, 0x41, 0x24, 0x85, 0xe8, 0xa2, 0xe0, 0xed, 0x25, 0xcb, 0x57, 0x49, 0xa0, 0x42,
	0x39, 0x9c, 0x5d, 0xc1, 0x5e, 0xdf, 0xcd, 0x1d, 0xd1, 0x12, 0x18, 0xe6, 0xf3, 0x79, 0xdd, 0x55,
	0x3a, 0x95, 0x4f, 0x2d, 0x74, 0x01, 0xfc, 0x5e, 0x80, 0xbe, 0x4d, 0xbd, 0x49, 0xd6, 0x66, 0xf6,
	0x16, 0xa2, 0x4f, 0xf5, 0xa2, 0xa8, 0xee, 0x9d, 0x3d, 0x3b, 0x84, 0xd8, 0xdc, 0xbc, 0xdd, 0x67,
	0x76, 0x06, 0x23, 0x8a, 0xf3, 0xcb, 0x9c, 0x2f, 0xf0, 0xfe, 0xdd, 0x3d, 0x80, 0xa0, 0xac, 0x2b,
	0x5c, 0xa9, 0x2c, 0x01, 0xd5, 0x20, 0x7b, 0x0e, 0xbb, 0x6b, 0xca, 0x3b, 0xa4, 0xdf, 0x41, 0xf4,
	0x45, 0x4e, 0x7a, 0xcb, 0x22, 0x07, 0xee, 0x7d, 0x8e, 0x21, 0xcc, 0x4b, 0xd7, 0xc6, 0x80, 0x1a,
	0x24, 0xc3, 0x99, 0xcb, 0xb7, 0x2b, 0xbc, 0xfe, 0x3b, 0x80, 0x9d, 0x6f, 0xf9, 0x4f, 0x24, 0x2f,
	0xc1, 0xff, 0x9a, 0xaf, 0xc8, 0xfe, 0x91, 0xfe, 0x50, 0xac, 0x3f, 0x0c, 0x29, 0xb9, 0x5e, 0x12,
	0x0d, 0x79, 0x01, 0x81, 0x7a, 0x3c, 0xe4, 0xa1, 0x39, 0xb4, 0xef, 0x2d, 0x7d, 0xb4, 0x59, 0x10,
	0x0d, 0x79, 0x05, 0xa1, 0x5e, 0x74, 0x62, 0xcf, 0xdc, 0xc3, 0x49, 0xf7, 0xaf, 0x55, 0x44, 0x43,
	0xde, 0x40, 0x64, 0x17, 0x88, 0x1c, 0xb8, 0xe3, 0xde, 0x7e, 0xa7, 0x4f, 0xb6, 0x54, 0xb5, 0x27,
	0x35, 0x4c, 0xe7, 0xc9, 0x2e, 0x85, 0xf3, 0xb4, 0x9e, 0xf5, 0xb1, 0x14, 0xd1, 0x03, 0x20, 0xc4,
	0xd1, 0xb9, 0x21, 0xa7, 0x8f, 0x6f, 0xd4, 0xb4, 0x80, 0x6a, 0xa8, 0x13, 0xb0, 0xb3, 0x71, 0x02,
	0xae, 0xdf, 0x17, 0xa1, 0xfa, 0xd2, 0x1e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x83, 0x82, 0x25,
	0xe4, 0x78, 0x05, 0x00, 0x00,
}
