// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Account.proto

package Account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisReq) Reset()         { *m = RegisReq{} }
func (m *RegisReq) String() string { return proto.CompactTextString(m) }
func (*RegisReq) ProtoMessage()    {}
func (*RegisReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_628bbec62b553e4f, []int{0}
}

func (m *RegisReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisReq.Unmarshal(m, b)
}
func (m *RegisReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisReq.Marshal(b, m, deterministic)
}
func (m *RegisReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisReq.Merge(m, src)
}
func (m *RegisReq) XXX_Size() int {
	return xxx_messageInfo_RegisReq.Size(m)
}
func (m *RegisReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisReq proto.InternalMessageInfo

func (m *RegisReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UeserId              int32    `protobuf:"varint,2,opt,name=ueser_id,json=ueserId,proto3" json:"ueser_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisResp) Reset()         { *m = RegisResp{} }
func (m *RegisResp) String() string { return proto.CompactTextString(m) }
func (*RegisResp) ProtoMessage()    {}
func (*RegisResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_628bbec62b553e4f, []int{1}
}

func (m *RegisResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisResp.Unmarshal(m, b)
}
func (m *RegisResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisResp.Marshal(b, m, deterministic)
}
func (m *RegisResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisResp.Merge(m, src)
}
func (m *RegisResp) XXX_Size() int {
	return xxx_messageInfo_RegisResp.Size(m)
}
func (m *RegisResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisResp proto.InternalMessageInfo

func (m *RegisResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisResp) GetUeserId() int32 {
	if m != nil {
		return m.UeserId
	}
	return 0
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_628bbec62b553e4f, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_628bbec62b553e4f, []int{3}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisReq)(nil), "Account.RegisReq")
	proto.RegisterType((*RegisResp)(nil), "Account.RegisResp")
	proto.RegisterType((*LoginReq)(nil), "Account.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "Account.LoginResp")
}

func init() { proto.RegisterFile("Account.proto", fileDescriptor_628bbec62b553e4f) }

var fileDescriptor_628bbec62b553e4f = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x75, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x1c, 0xb8,
	0x38, 0x82, 0x52, 0xd3, 0x33, 0x8b, 0x83, 0x52, 0x0b, 0x85, 0x24, 0xb8, 0xd8, 0x13, 0x21, 0xc2,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x14, 0x17, 0x47, 0x41, 0x62, 0x71,
	0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x58, 0x0a, 0xce, 0x57, 0x72, 0xe0, 0xe2, 0x84, 0x9a,
	0x50, 0x5c, 0x00, 0x32, 0x22, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x15, 0x66, 0x04, 0x94, 0x2b,
	0x24, 0xc9, 0xc5, 0x51, 0x9a, 0x5a, 0x9c, 0x5a, 0x14, 0x9f, 0x09, 0x31, 0x82, 0x35, 0x88, 0x1d,
	0xcc, 0xf7, 0x04, 0x99, 0xc0, 0xe1, 0x93, 0x9f, 0x9e, 0x99, 0x47, 0xbe, 0x1b, 0x54, 0xb9, 0x38,
	0xa1, 0x26, 0xe0, 0x73, 0x83, 0x51, 0x01, 0x17, 0xcc, 0xdf, 0x42, 0xc6, 0x50, 0x7f, 0x97, 0xa4,
	0x16, 0x09, 0x09, 0xea, 0xc1, 0x02, 0x07, 0x16, 0x14, 0x52, 0x42, 0xe8, 0x42, 0xc5, 0x05, 0x4a,
	0x0c, 0x42, 0x06, 0x5c, 0xac, 0x60, 0x6b, 0x90, 0x74, 0xc0, 0x1c, 0x8e, 0xa4, 0x03, 0xee, 0x12,
	0x25, 0x86, 0x24, 0x36, 0x70, 0x70, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0x78, 0xf5,
	0x6f, 0x7f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	Register(ctx context.Context, in *RegisReq, opts ...grpc.CallOption) (*RegisResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Register(ctx context.Context, in *RegisReq, opts ...grpc.CallOption) (*RegisResp, error) {
	out := new(RegisResp)
	err := c.cc.Invoke(ctx, "/Account.Account/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/Account.Account/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	Register(context.Context, *RegisReq) (*RegisResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) Register(ctx context.Context, req *RegisReq) (*RegisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAccountServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account.Account/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Register(ctx, req.(*RegisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Account_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Account.proto",
}
