// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEMALE",
	2: "MALE",
}

var Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"FEMALE":  1,
	"MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type RegisterReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterReq) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type RegisterResp struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type QueryUserReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserReq) Reset()         { *m = QueryUserReq{} }
func (m *QueryUserReq) String() string { return proto.CompactTextString(m) }
func (*QueryUserReq) ProtoMessage()    {}
func (*QueryUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *QueryUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserReq.Unmarshal(m, b)
}
func (m *QueryUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserReq.Marshal(b, m, deterministic)
}
func (m *QueryUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserReq.Merge(m, src)
}
func (m *QueryUserReq) XXX_Size() int {
	return xxx_messageInfo_QueryUserReq.Size(m)
}
func (m *QueryUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserReq proto.InternalMessageInfo

func (m *QueryUserReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type QueryUserResp struct {
	QueryUser            *UserInfo `protobuf:"bytes,1,opt,name=query_user,json=queryUser,proto3" json:"query_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryUserResp) Reset()         { *m = QueryUserResp{} }
func (m *QueryUserResp) String() string { return proto.CompactTextString(m) }
func (*QueryUserResp) ProtoMessage()    {}
func (*QueryUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *QueryUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserResp.Unmarshal(m, b)
}
func (m *QueryUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserResp.Marshal(b, m, deterministic)
}
func (m *QueryUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserResp.Merge(m, src)
}
func (m *QueryUserResp) XXX_Size() int {
	return xxx_messageInfo_QueryUserResp.Size(m)
}
func (m *QueryUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserResp proto.InternalMessageInfo

func (m *QueryUserResp) GetQueryUser() *UserInfo {
	if m != nil {
		return m.QueryUser
	}
	return nil
}

// User信息, 应当在登录成功后返回给client, 需要给client知道的信息就往这里面加
type UserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("account.Gender", Gender_name, Gender_value)
	proto.RegisterType((*RegisterReq)(nil), "account.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "account.RegisterResp")
	proto.RegisterType((*QueryUserReq)(nil), "account.QueryUserReq")
	proto.RegisterType((*QueryUserResp)(nil), "account.QueryUserResp")
	proto.RegisterType((*UserInfo)(nil), "account.UserInfo")
	proto.RegisterType((*LoginReq)(nil), "account.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "account.LoginResp")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4b, 0x4f, 0xea, 0x40,
	0x14, 0xc7, 0x19, 0x2e, 0xf4, 0x71, 0x80, 0x7b, 0xb9, 0x27, 0x3e, 0x9a, 0xae, 0xc8, 0x6c, 0x20,
	0x9a, 0x10, 0x82, 0x1b, 0x8d, 0x1b, 0x59, 0xa0, 0x21, 0x22, 0xc6, 0x26, 0xc4, 0x25, 0x41, 0x3a,
	0x90, 0xc6, 0x38, 0x53, 0x3a, 0x34, 0xc6, 0x9d, 0xf1, 0x13, 0xf9, 0x11, 0x4d, 0x87, 0x4e, 0x69,
	0x14, 0xa2, 0x71, 0x77, 0xce, 0xff, 0x3c, 0xf8, 0xf1, 0x3f, 0x53, 0xa8, 0x4d, 0x67, 0x33, 0x11,
	0xf3, 0x55, 0x3b, 0x8c, 0xc4, 0x4a, 0xa0, 0x99, 0xa6, 0xf4, 0x95, 0x40, 0xc5, 0x63, 0x8b, 0x40,
	0xae, 0x58, 0xe4, 0xb1, 0x25, 0x3a, 0xa0, 0x4b, 0x0e, 0x69, 0x90, 0x96, 0xed, 0xe9, 0x14, 0x5d,
	0xb0, 0xc2, 0xa9, 0x94, 0xcf, 0x22, 0xf2, 0x9d, 0xa2, 0x2a, 0x65, 0x39, 0x22, 0x94, 0xf8, 0xf4,
	0x89, 0x39, 0x7f, 0x94, 0xae, 0x62, 0x6c, 0x82, 0xb1, 0x60, 0xdc, 0x67, 0x91, 0x53, 0x6a, 0x90,
	0xd6, 0xdf, 0xee, 0xbf, 0xb6, 0x46, 0xb8, 0x52, 0xb2, 0x97, 0x96, 0x69, 0x13, 0xaa, 0x1b, 0x02,
	0x19, 0xe2, 0x21, 0x98, 0xb1, 0x64, 0xd1, 0x24, 0xf0, 0x15, 0x42, 0xcd, 0x33, 0x92, 0x74, 0xe0,
	0xd3, 0x16, 0x54, 0xef, 0x62, 0x16, 0xbd, 0x8c, 0xe5, 0x37, 0xac, 0xb4, 0x07, 0xb5, 0x5c, 0xa7,
	0x0c, 0xb1, 0x03, 0xb0, 0x4c, 0x84, 0x49, 0xb2, 0x4a, 0x75, 0x57, 0xba, 0xff, 0x33, 0xa0, 0xa4,
	0x6d, 0xc0, 0xe7, 0xc2, 0xb3, 0x97, 0x7a, 0x8a, 0xbe, 0x11, 0xb0, 0xb4, 0xbe, 0x13, 0x29, 0x8f,
	0x50, 0xfc, 0x62, 0x17, 0x0f, 0x66, 0x8f, 0x39, 0x5b, 0xb2, 0xfc, 0xe7, 0xd6, 0x5c, 0x80, 0x35,
	0x14, 0x8b, 0x80, 0xff, 0xfa, 0x32, 0xf4, 0x1c, 0xec, 0x74, 0x83, 0x0c, 0xb1, 0x0d, 0xf6, 0xfa,
	0x6f, 0xf0, 0xb9, 0xd8, 0x6d, 0x82, 0x15, 0xa7, 0xd1, 0xd1, 0x31, 0x18, 0x6b, 0x20, 0xac, 0x80,
	0x39, 0x1e, 0x5d, 0x8f, 0x6e, 0xef, 0x47, 0xf5, 0x02, 0x02, 0x18, 0x97, 0xfd, 0x9b, 0xde, 0xb0,
	0x5f, 0x27, 0x68, 0x41, 0x49, 0x45, 0xc5, 0xee, 0x3b, 0x01, 0xb3, 0x97, 0x12, 0x9d, 0x81, 0xa5,
	0x4f, 0x8a, 0x7b, 0xd9, 0x2f, 0xe4, 0xde, 0x99, 0xbb, 0xbf, 0x45, 0x95, 0x21, 0x2d, 0x60, 0x07,
	0xca, 0x0a, 0x18, 0x37, 0x64, 0xda, 0x02, 0x17, 0x3f, 0x4b, 0x6a, 0xe2, 0x14, 0xca, 0xea, 0xd8,
	0xb8, 0xd9, 0x99, 0x7f, 0x26, 0xee, 0xc1, 0x36, 0x39, 0x99, 0x7c, 0x30, 0xd4, 0xc7, 0x70, 0xf2,
	0x11, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xe6, 0x0b, 0x51, 0x1d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Query(ctx context.Context, in *QueryUserReq, opts ...grpc.CallOption) (*QueryUserResp, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/account.Account/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/account.Account/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Query(ctx context.Context, in *QueryUserReq, opts ...grpc.CallOption) (*QueryUserResp, error) {
	out := new(QueryUserResp)
	err := c.cc.Invoke(ctx, "/account.Account/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Query(context.Context, *QueryUserReq) (*QueryUserResp, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAccountServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAccountServer) Query(ctx context.Context, req *QueryUserReq) (*QueryUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Query(ctx, req.(*QueryUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Account_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Account_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
